### ISSUE TITLE
[BUG] Two lasers colliding, end to end

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#101]
Let` |>` be a cannon firing right
Let `<|` be a cannon firing left
Let `--` be lasers
Let `__` be an empty cell
Let `X` be a robot

This specific scenario:
`|>----------------------<|`

If a robot enter the laser, this will happen:
`|>---------X___________<|`

What should happen:
`|>---------X-----------<|`

HOWEVER: This scenario does not appear in any of the maps we intend to make.
Because the issue will not appear in actual maps, this will not be fixed

**Comment by buzzdead** [comment]
Kunne vært moro å lagt til hvis vi får tid til overs. Er ikke noe vanskelig å legge det til i findCannon, bare en sjekk om den andre posisjonen også har kannon egentlig, men er noen etterhengende ting som må fikses hvis man gjør det slik tror jeg.

**Comment by adipid** [comment]
@buzzdead, er dette et problem lenger?

**Comment by buzzdead** [comment]
Det er ikke et problem med mindre noen insisterer på å lage maps hvor laserne står rettet imot hverandre.

**Comment by adipid** [comment]
Dette er ikke et reelt problem for vår MVP, så jeg lukker denne.
