### ISSUE TITLE
Som <spiller> har jeg lyst til å <se de ulike kortene de andre spillerene har> for <å kunne planlegge mine neste steg>

### ISSUE THREAD

**Issue by timharek** [inf112-v20/crawling-crow#106]
## Akseptansekriterier
- [ ] Oversikt på de ulike programkortene til de andre spillerene.

## Definisjonen av ferdig
- [ ] #136

**Comment by buzzdead** [comment]
Jeg har tenkt litt på dette, og kommet fram til at er det er egentlig fornuftig som spiller å ha oversikt over alle kortene til alle ai robotene? Antakeligvis har man mer lyst til å finne ut litt om en eller to spesifikke roboter som er i nærheten av deg selv, og som er av betydning i forhold til dine neste kort. Kanskje kunne det vært greiest å få opp en spreadsheet med informasjon når du holder musa over leaderboardet til den roboten du ønsker å få litt informasjon om? Sånn som last played cards (i forhold til locked register cards), hva slags styring roboten har (Styrt av AI, styrt av spiller). Hvor mye hp den har, hvor mange reboots den har osv..
