### ISSUE TITLE
Conveyor belts

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#109]
Implementere fungerene samlebånd, basert på hva som er på spillbrettet.

- [x] Samlebånd
- [x] Roterende samlebånd
- [x] Ekspress samlebånd (dobbel hastighet)

Definisjon av ferdig:
Robotene blir beveget slik som bildene antyder i kommentarfeltet.

**Comment by buzzdead** [comment]
La til en enkel implementasjon i midlertid for dette.

**Comment by adipid** [comment]
![Skjermbilde 2020-03-25 kl  09 41 36](https://user-images.githubusercontent.com/5453010/77517693-dd898a00-6e7c-11ea-937f-ac0537194fdb.png)

**Comment by adipid** [comment]
![Skjermbilde 2020-03-25 kl  09 44 28](https://user-images.githubusercontent.com/5453010/77517930-39eca980-6e7d-11ea-8a42-7a7fc28f6f37.png)
