### ISSUE TITLE
[BUG] Changing map while in "full screen" causes issues.

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#115]
The best way to use the application as it is right now is to play in default or full screen, then resize back to default before changing a map, and so on.
Currently you have to resize back to normal resolution before changing a map because of how changeMap() works, it practically nulls out all the data and then runs UI again with the new map's ID. 
Currently resizing works well with respect to both the menu and the game, but we will have to find out a way to make it all work. I know there's some controversy with using center camera as it kind of stretches out the tiles a little bit, but its a nice temporary way to make it all seem ok.

**Comment by buzzdead** [comment]
Think the easiest way around this might be to just make the change map function change map without restarting the whole game.

**Comment by adipid** [comment]
@buzzdead skriv på norsk er du grei, så vi holder det konsekvent med de andre issuene :)
