### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#116]
- [x] Lage et pent brukergrensesnitt (grafisk), som er konsekvent og fungerer sammen med hvordan spillet kjører som også minner om brettspillet.
- [x] Implementere det grafiske UI.

**Comment by adipid** [comment]
![Game window](https://user-images.githubusercontent.com/5453010/77238927-6f6f6980-6bd5-11ea-93ce-3e860ce992ea.png)

Det vi har blitt enige om til nå.

**Comment by adipid** [comment]
![Game window](https://user-images.githubusercontent.com/5453010/78558144-6821a000-7812-11ea-804c-16456bee4cef.png)

**Comment by adipid** [comment]
# Fullskjerm 16:9
![ui](https://user-images.githubusercontent.com/5453010/78570188-ef780f00-7824-11ea-8306-f252f0dc2456.png)


## Elementer
### Power down
| Type  |  Bilde |
|---|---|
| Power-down  |  ![power-down](https://user-images.githubusercontent.com/5453010/78570512-5eedfe80-7825-11ea-9127-4ba1792811a9.png)  |
| Powered-down | ![powered-down](https://user-images.githubusercontent.com/5453010/78570527-644b4900-7825-11ea-9a64-fa93dbc4d52e.png)  |
|  Powering-down | ![powering-down](https://user-images.githubusercontent.com/5453010/78570758-abd1d500-7825-11ea-835a-dcd960a674dc.png)  |

### Reboots
| Type  | Bilde  |
|---|---|
| Active reboot  | ![reboot-active](https://user-images.githubusercontent.com/5453010/78571210-3c101a00-7826-11ea-9282-dbc18251ea27.png) |
| Inactive reboot  | ![reboot-inactive](https://user-images.githubusercontent.com/5453010/78571282-4d592680-7826-11ea-8173-b98acec796f7.png)  |

### Damage tokens
| Type  | Bilde  |
|---|---|
| Damage token card  |  ![damage-token-card](https://user-images.githubusercontent.com/5453010/78571481-86919680-7826-11ea-95c4-de3159fec664.png) |
| Damage token card: red | ![damage-token-card-red](https://user-images.githubusercontent.com/5453010/78571677-c3f62400-7826-11ea-8827-390412d4f7ef.png) |
| Damage token: red  |  ![damage-token-red](https://user-images.githubusercontent.com/5453010/78571514-914c2b80-7826-11ea-8497-0ab79723b2b5.png) |
| Damage token  |  ![damage-token](https://user-images.githubusercontent.com/5453010/78571567-a1fca180-7826-11ea-9d6a-c7d3f462fefd.png) |

### Done-knapp
| Type | Bilde |
|---|---|
| Done | ![done-button](https://user-images.githubusercontent.com/5453010/78571789-ed16b480-7826-11ea-9c4e-28a3e83047c6.png) |
| Done-pressed | ![done-button-pressed](https://user-images.githubusercontent.com/5453010/78571806-f273ff00-7826-11ea-9206-27fd77ec3f3e.png) |

**Comment by adipid** [comment]
@thomashusebo og jeg har prøvd å legge til reboots nå, men det ser ut til å være en utrolig for å få dette til å bli `draw()`'et mtp at vi trenger `Robot.getReboots()`, og vi alltid har lyst å kunne se antall reboots og livs etc...

**Comment by adipid** [comment]
# BUG
Oppdaget en bug mtp skjermstørrelse, hvis skjermen er mindre 1920x1080, da kan UI elementene hover/klikk-posisjonen bli forskyvet.

**Comment by adipid** [comment]
> @thomashusebo og jeg har prøvd å legge til reboots nå, men det ser ut til å være en utfordring for å få dette til å bli `draw()`'et mtp at vi trenger `Robot.getReboots()`, og vi alltid har lyst å kunne se antall reboots og livs etc...

@buzzdead, har du noe forslag til hvordan dette kan gjøres? Jeg ser ingen måte å gjøre dette på akkurat nå.

**Comment by buzzdead** [comment]
Ja altså det må i beste tilfelle oppdateres ett sted hvor det tegnes hver gang antall reboots forrandrer seg for en enkelt robot. Eventuelt kan det oppdateres ett sted for hver runde(noe som medfører at en robot kan ødelegges, men at antall reboots oppdaterer seg først neste runde), en tredje løsning kunne vært at klasse metoden som tegner antall reboots for en og alle roboter oppdateres for hver fase.

**Comment by adipid** [comment]
- [ ] **Reboots**-UI burde oppdateres hver `checkForDestroyedRobots()`.
- [ ] **Liv**-UI burde oppdateres hver `fireLasers()` `crash()` kjøres.

**Comment by adipid** [comment]
Ser nå at UI'et blir litt rart når man har lav oppløsning fra begynnelsen, 40ccc6f9ca57ecce0f48edfd999a753e2289f935.

Så lurer egentlig på om vi burde ha en sjekk for oppløsningen til brukeren, mtp at UI elementene må skaleres ned da

**Comment by adipid** [comment]
Har nå fått på plass UI unntatt leaderboard, da dette blir ansett som _nice to have_
