### ISSUE TITLE
Move and change playNextCard method

### ISSUE THREAD

**Issue by ljo071** [inf112-v20/crawling-crow#117]
- [ ]  Flytte `playNextCard()` fra `Robot`-klassen til `ProgramCards`-klassen
- [x]  Forandre `playNextCard()` til et `HashMap`

**Comment by adipid** [comment]
Anser det ikke nødvendig lenger å flytte `playNextCard()`, med tanke på at det ikke er en enkel løsning på flytte denne til `ProgramCards`-klassen siden bevegelesemetodene ligger i `Robot`-klassen.
