### ISSUE TITLE
[BUG] Conveyorbelt rotation only works when facing the right way

### ISSUE THREAD

**Issue by ljo071** [inf112-v20/crawling-crow#118]
Conveyorbelt roterer helt til den er plassert "riktig vei" i forhold til pilen og så beveger seg, den skal egentlig bare rotere en gang og så bevege seg.

**Comment by buzzdead** [comment]
Etter reglene skal man roteres i det man havner oppe på et roterende belte, om man allerede står oppe på et roterende belte så skal man bevege seg i retningen det roterende beltet peker.
