### ISSUE TITLE
Preparation for Oblig3 hand-in

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#122]
- [ ] ~Fullfør cleanup #103~
- [x] Fullføre markdown-fil
- [x] Klassediagram
- [x] Oppdater readme
- [x] Lage flere tester (manuelle/automatiske)
- [ ] Fikse innleveringstekst iht Codacy
- [ ] Lag release
    - [x] Lag egen innleveringsbranch
    - [x] Fjern TODO's etc, 
    - [x] Merge med master

**Comment by ljo071** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/59846048/77762946-98ab5200-703a-11ea-8993-dce653775105.jpg)
Laget et flott klassediagram

**Comment by adipid** [comment]
![Skjermbilde 2020-03-27 kl  15 23 27](https://user-images.githubusercontent.com/5453010/77765692-ea55db80-703e-11ea-9ad3-a9c602615159.png)

**Comment by adipid** [comment]
![Skjermbilde 2020-03-27 kl  15 51 18](https://user-images.githubusercontent.com/5453010/77768468-ceeccf80-7042-11ea-9658-c740dc1dfb8a.png)
