### ISSUE TITLE
[BUG] Minimizing game window 

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#126]
Minimere spillvinduet medfører et par bugs.

- [x] Før man trykker "Start New Game", dersom applikasjonsvinduet først blir minimert eller gjemt bak andre applikasjonsvinduer, for å så dra fram applikasjonsvinduet igjen. Da er menyen blitt borte og man ser bare et tomt kart. 
Presser man "M" for å få opp menyen igjen, er man tilbake der man skal være.

- [x] Dersom man er inne i spillet, trykker "ENTER" for å få opp Programmeringskort. Dersom man da minimerer og får vinduet tilbake, så kan man ikke lenger trykke på programkortene. 
Presser man "ENTER" igjen, får man opp nye kort, men ellers fungerer det som normalt igjen.

**Comment by buzzdead** [comment]
Var bare snakk om funksjonaliteten til libgdx. Resume blir kalt på automatisk ved at man klikker seg ut av spillet med alt tab eller åpne andre vinduer på PCen som ikke har med spillet å gjøre.

**Comment by adipid** [comment]
Så denne er fikset nå da?
