### ISSUE TITLE
[BUG] Changing from FunMode "On" to FunMode "Off"

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#127]
Når man er i et "FunMode" spill, men velger å starte et nytt spill med "FunMode" slått av. Da blir ikke de overflødige robotene fjernet fra mappet.

Man kan komme seg rundt dette ved å bytte map.

**Comment by buzzdead** [comment]
Tror fun mode begynner å bli ganske deprecated da det ikke var ment for å teste det nye vi har lagt til, mer ment for å teste bevegelse og interaksjon med spillets funksjoner, noe vi forsåvidt har lagt bak oss nå.
