### ISSUE TITLE
[userRobot] can move outside the map

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#128]
Trenger at `Robot` man styrer selv kan gå utenfor kartet.

**Comment by buzzdead** [comment]
Den henger sammen med graveyard position. Så sjekken i robotview om roboten havner utenfor kartet kan kanskje forrandres til en sjekk om roboten er i graveyard, hvis ikke så beveger den seg hvor enn det skulle være.

**Comment by adipid** [comment]
Denne er ikke fikset, så ingen vits å lukke issuen.

**Comment by buzzdead** [comment]
Joda, var noe trøbbel med å pushe bare i forbindelse med task & context, fant ut av det nå.
