### ISSUE TITLE
[UI] Seperate game into different Screens

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#129]
Det vil skape bedre oversikt og mer fleksibilitet å implementere screens fremfor å ha det sånn som det er nå. Før videre implementasjon av issues og brukerhistorier bør vi sette spillet til å være en screen, og menyen til å være en screen. En refaktorering som fullfører det som ble gjort i #92  på en skikkelig måte, samt kanskje en egen screen for valg av kart og en for nettverksdelen.

**Comment by adipid** [comment]
Det var jo slik jeg sa vi burde gjøre det fra begynnelsen av. Dette vil være en ganske omfattende refaktorering mtp hvordan ting er gjort nå, så er usikker på om vi burde prioritere dette nå. I tillegg burde nettverk være siste prioritering også.

**Comment by adipid** [comment]
Ved å gjøre dette vil nok dette fikse feilen #126

**Comment by adipid** [comment]
Så vidt så jeg ser det nå, er dette ikke like gunstig å gjøre lenger mtp hvor mye som faktisk må refaktoreres.

**Comment by adipid** [comment]
Bare å gjenåpne denne hvis den blir relevant igjen.
