### ISSUE TITLE
Make tests for mandatory1

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#13]
Lage tester for oblig1.

Det ser ut til å være mulig ved bruk av *headless* mode.

**Comment by adipid** [comment]
Lagde tester som ikke fungerer forløpig. Fordi vi ikke forstår helt Libgdx.

Kan være mulig å kjøre med headless mode.

**Comment by adipid** [comment]
`RobotTest` ikke kjører, det er fordi `Robot robot = new Robot()` ikke kjører i `create()`-metoden i `GameBoard` som kreves av Libgdx. Derfor krasjer testene før de får kjørt.

**Comment by buzzdead** [comment]
Hvis du prøver å kjøre robottest i den nye branchen (progress) så spesifiserer assetmanager hva som går feil.

**Comment by adipid** [comment]
Ser ut til at dette vil være mulig etter at #21 er ferdig implementert. Da vil vi prioritere å lage tester for **foretningslogikk** framfor **UI**

**Comment by thomashusebo** [comment]
Fra Elise Fiskeseth, gruppeleder i dag:
Hei! Jeg har snakket med Siv og dere trenger ikke teste gui. Så lenge logikk er testet tilstrekkelig holder det for nå. Logikk som vil være mulig å teste for nå kan feks være om et koordinat til en posisjon settes riktig, og at om x koordinatet settes så endres ikke y koordinatet. :smile:
