### ISSUE TITLE
[Robot] rebooting into an occupied Archive Marker

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#130]
Når en robot blir satt til siste arkiverte checkpoint ved å reboote i begynnelsen av runden så skal den enten havne i Virtual Mode eller på en av de fire posisjonene roboten kan bevege seg til fra den arkiverte posisjonen #107. Jeg foreslo virtual mode, men det har ikke blitt implementert helt slik som det skal være.

**Comment by adipid** [comment]
Dette er hva regelboken vi har fått sier, så tenker vi skal følge den.

![Skjermbilde 2020-03-29 kl  20 17 24](https://user-images.githubusercontent.com/5453010/77856852-4f096580-71fa-11ea-9499-1dda56522baa.png)

**Comment by buzzdead** [comment]
Ja er ikke veldig mulig å bruke Virtual Mode så lenge tilgangen til enhver robot foregår i samme layer. Prøver man f.eks å rotere en robot i virtual mode så roterer man også den faktiske roboten som står på posisjonen.
