### ISSUE TITLE
[Object] ArchiveMarker as an Object

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#131]
I forbindelse med issues: #113 #111 med #171.
Gjøre ArchiveMarker til et objekt med en funksjon. For eksempel kan en Wrench ArchiveMarker gi ett hp, og en WrenchHammer ArchiveMarker gi to hp og ett option card. Da slipper man å inkludere dette i sjekken i fasene, også kan man heller sjekke om roboten har disse objektene ved enden av runden, (har betyr i denne sammenhengen at den stod på posisjonen i siste fase). Kanskje unødvendig å gjøre det for komplisert da det virker som det kun er disse to objektene som er relevante i enden av runden for den originale versjonen av roborally.

**Comment by adipid** [comment]
Tenker dette ikke er en prioritet foreløpig, vi kan refaktorere dette når vi har fått på plass MVP.

**Comment by buzzdead** [comment]
Tror ikke det er særlg aktuelt å begynne med dette issuet nå, closer det.

**Comment by adipid** [comment]
Ingen grunn til å lukke den, det er jo **nice to have**, vi er ikke nødt til å ha fullført alle issues når vi leverer :)
