### ISSUE TITLE
When a last player has yet to chose cards, a counter starts counting down

### ISSUE THREAD

**Issue by ljo071** [inf112-v20/crawling-crow#134]
- [x] Nedtelling når det er en igjen som må velge kort
- [x] Nedtellingen er på 30 sek

**Comment by buzzdead** [comment]
Siden det ikke er meget aktuelt å implementere noe særlig nettverk burde kanskje heller denne funksjonen være tilfeldig. 1/8 sjanse at du er treigere enn datamaskinen og bare får 30 sekunder på å velge kort.

**Comment by thomashusebo** [comment]
Siden vi inntil videre ikke kommer til å implementere nettverk og bruker AI, så vil det i sin enkleste form være tilstrekkelig i første omgang å gi alle spillere 30 sekunder å programmere roboten sin. 

- [ ] Nedtelleren skal telle ned sekunder fra 30. 
- [ ] Nedtelleren må ha et grafisk element som indikerer hvor mye tid som er igjen. 
- [ ] Hvis alle spillere har programmert roboten sin, så stopper nedtelleren og forsvinner fra UI
- [ ] Hvis nedtellingen når 0, så skal det velges tilfeldige kort til resterende velges tilfeldig

Når dette er på plass, så legge til slik at når alle untatt 1 spiller har valgt kort, så starter tidnedtakeren.

**Comment by ljo071** [comment]
#147
