### ISSUE TITLE
Detailed handling of programcards

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#135]
Brukerhistorier:
#54 
#65

Def:
"Deck of Cards"/kortstokk er hvor spillere trekker sine kort fra
"Cards in hand"/kort på hånden: antallet er 9 på starten av første runde.
"Cards Selected"/kort som er valgt/Programmere robot/Kort plassert i register: antallet er 5 på starten av første runde.
"Discard pile"/boss haug er de kortene som er ut av spillet 

- [x] Trekke kort
    - [x] På starten av en runde, skal hver spiller få antall kort fra kortstokken lik helsen sin minus 1.
- [x] Programmere robot
    - [x] Når en spiller skal programmere vidoen/fylle sin "register", så må spilleren fylle opp alle ledige plasser i registeret
    - [x] Når en spiller er ferdig å programmere sin robot skal de resterende kortene legges i boss haugen
- [x] På slutten av en runde, under clean-up, for hver robot:
    - [x] Låse registere dersom:
        - [x] Hvis helsen er 6, skal ingen kort i register låses
        - [x] Hvis helsen er 5, skal det siste kortet i registeret låses
        - [x] Hvis helsen er 4, skal de 2 siste kortet i registeret låses
        - [x] Hvis helsen er 3, skal de 3 siste kortet i registeret låses
        - [x] Hvis helsen er 2, skal de 4 siste kortet i registeret låses
        - [x] Hvis helsen er 1, skal alle 5 kortetene i registeret låses
    - [x] Alle kort i registeret som ikke er låst, skal legges i bosshaug
- [x] Når NPC roboter spiller må kort puttes i register på samme måte.

**Comment by thomashusebo** [comment]
Spørsmål

For å kunne legge til låsing av kort så prøver jeg å forstå hvordan kortene faktisk blir valgt av spiller. Dette leder meg til ProgramCardsView og til metoden MakeSomething. 
- Spørsmål 1: Forstår jeg rett: MakeSomething lager det grafiske til ETT spesifikt kort?
- Spørsmål 2: Er det Listener her som tar for seg all forretningslogikk ved valg av kort? Eller skjer dette også andre steder? @adipid  @buzzdead

**Comment by buzzdead** [comment]
MakeSomething lager en gruppe med bildet av det gjeldene kortet, en label for prioritet og en label for indeks nummer i forhold til hvilken orden man velger å spille det i. Funksjonaliteten ved å trykke på kort finner du i clicklistener i samme klasse, den tar indexen fra kortene slik som de var og binder de til en kronologisk rekkefølge i order[ ]. Hvis man ønsker å ordne slik at man ikke kan trykke done før man har valgt gitt antall kort kan man kikke i click listener for donebutton.

**Comment by buzzdead** [comment]
Og linje 181, metode done() er den som avgjør om man er ferdig med å klikke på kort eller ikke.

**Comment by thomashusebo** [comment]
Per nå har jeg fått det meste på plass, men mangler en vesentlig ting. Når kort er lockdown, så vi endre antall kort som velges. 

Hva jeg ønsker:
- Hvis ett kort er låst, så er kortet i register posisjon 0 igjen fra forrige runde. 
- Vi skal da altså fylle i register posisjoner 1 til 4. 

Hva jeg lurer på: 
- Hvor må jeg sette start-indexen til 1? Forslag til god måte å importere tallet 1 fra robotLogic? @buzzdead

**Comment by thomashusebo** [comment]
Stuff to do:
- [ ] Fjern deprecated kode: nextCard i RobotLogic
- [ ] Få sørget for at korrekt antall kort velges når noen kort er i lockdown

**Comment by buzzdead** [comment]
Jeg må nesten kikke litt på hva du mener, du har en pekepinne til en manuell test jeg kan gjøre eller er det åpentbart om jeg tester litt?

**Comment by thomashusebo** [comment]
Angående deprecated. Helt enig, deprecated skal vekk, men jeg bare skrev det her som en huskeliste. Usikker hvor mye mer jeg får gjort akkurat med en gang.

Angående låsing av registre, så har du helt rett. Låsingen av registre mener jeg skal funke bra. Siden det er en egen klasse, så blir det også enkelt å lage automatiske tester. Selve "låsingen" skal fungere ved mindre jeg har svimlet litt. **Så det er IKKE dette jeg spør om**. 

Måten jeg har gjort det på er at "Cleanup" fjernes alle nødvendig kort fra registre. Her regner den ut hvor mange kort som skal "låses" == ikke fjernes fra register. Vi skal bare fylle på resterende plassene. For å få dette til, ønsker jeg å endre hva som er "første ulåste posisjon". 

For å teste dette i konsoll kan du bruke register.toString() for å skrive ut hvilke kort som ligger i Register. Men dette hjelper ikke på problemet mitt. 

**Det jeg trenger å vite** er hvordan ProgramCardView bestemmer seg for hvilke plass den skal sette en kort. Default slik det er nå, er at den plasserer kort på plass 0,1,2,3,4. Det er i prinsippet bare en rekke med tall som starter på `a`=0 og slutter på `b`=4. Jeg vet hvordan jeg endrer `b`. (det er gjort i ClickEvent), men jeg er usikker på hvor jeg endrer `a`.

**Comment by thomashusebo** [comment]
**Known bug** Det er dette som vil løse seg når jeg får svar på spørsmålet over: Alle spillere velger alltid 5 kort, men hvis en spiller er skadet for mye, så fjernes ikke alle kort fra registeret, slik det er nå (se spørsmålet mitt over). Dette medfører at registeret blir overfylt. Fix: Sørg for å bare trekke antall kort som mangler i register (se spørsmålet mitt over).

**Comment by buzzdead** [comment]
Jeg regner med at du ønsker å bruke en liste (order) på størrelsen 5 uansett hvor mange kort man skal spille da.. skal kikke på det etterpå, en idé er å reversere. En bedre idé er å kanskje skifte på den cardPick til å starte som 1 istedenfor null, og luke ut alle posisjoner i order som er lik -1, men du gjorde om slik at posisjonene ikke er initialisert til -1 så jeg.

**Comment by thomashusebo** [comment]
Posisjonene er fortsatt initialisert til å være -1, jeg har være fjernet hardkoding av tallet 5. 
```java
this.order = new int[SettingsUtil.REGISTER_SIZE];
Arrays.fill(order, -1);
```

**Comment by thomashusebo** [comment]
Og nei, jeg ønsker ikke å velge 5 uansett. Hvis det mangler 3 i register, så ønsker jeg bare å velge 3

**Comment by buzzdead** [comment]
Hvis cardPick blir initalisert til 1 så starter den jo i posisjon 1 i arrayet.

**Comment by thomashusebo** [comment]
ok dok, får leke med cardPick da

**Comment by buzzdead** [comment]
Laster ned branchen nå så kan jeg kikke på det litt senere selv.

**Comment by thomashusebo** [comment]
Ok. Skriver automatisk tester til Register klassen nå hvertfall

**Comment by buzzdead** [comment]
Hvis du velger cardPick til den posisjonen "a" skulle være, og utelukker alle posisjoner med verdi -1 i det man returnerer den greia i doneLabel så burde vel det oppfylle kravene, skal fungerer i praksis men har ikke testet så vet ikke.

**Comment by buzzdead** [comment]
Hvis du har lyst til å gjøre litt refaktorering i den klassen i samme slengen så ser jeg at om man tar imot en string som en variabel når man oppretter kort i game og kaller på f.eks makeMove3, så kan man bare ha en metode kalt makeCard(String cardName, int priority) istedenfor en metode for alle de forskjellige kortene.
