### ISSUE TITLE
[UI] Reveal registercards during play

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#136]
Brukerhistorie:
#234 

Når programkort spilles fra hvert register, så skal dette kortet bli synlig i spillvinduet

**Comment by buzzdead** [comment]
I forbindelse med denne og det andre issuet #164 så tenkte jeg mens jeg jobbet med LeaderBoard klassen #173 implementert i branchen 'leaderboard' at det kan være fornuftig å ha dette på høyre siden av kartet. Det kuleste hadde kanskje vært at man ser 5 kort der, hvor alle kort opp til fase nummeret man for tiden er i vises for hver robot's hånd med kort. Resten av kortene kan være face down hvor man bare ser grafikken på baksiden av kortet, kanskje noe av samme utseende som et distinkt område av grafikken til bakgrunnen til menyen vi velger å bruke.

**Comment by adipid** [comment]
@buzzdead holder du fremdeles på med denne? Ellers tror jeg vi bare dropper dette, med tanke på hvor lite tid vi har igjen.

**Comment by buzzdead** [comment]
Tror ikke det er så mye poeng, jeg tro denne funksjonen er mest for at man skal se at de andre ikke jukser egentlig.
