### ISSUE TITLE
Change the indicator for different tilelayers

### ISSUE THREAD

**Issue by ljo071** [inf112-v20/crawling-crow#137]
Indikator for ulike tilelayers skal være enum eller id, ikke string

**Comment by adipid** [comment]
- Klassen `Layers` er redusert med 226 linjer.
- Nå bruker `LayerName` i stedenfor _Strings_ og `layerNames.txt`.

Alt fungerer som før, men man bruker mer generiske metoder som skal være minst like lette å skjønne mtp. at man bare må definere hvilken `LayerName` det er snakk om.
