### ISSUE TITLE
See PriorityLabel without selecting program card

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#140]
Akkurat nå er det ikke mulig å se prioritet på programkortet uten å klikke på det.

**Comment by adipid** [comment]
@buzzdead, jeg prøvde å løse dette men ser på ingen måte hvordan teksten blir `draw()`'et etter at man har klikket på. Blir dette gjort i `ProgramCardsView` eller i `AnimateEvents`, eller ingen av stedene?

**Comment by buzzdead** [comment]
Prøv å skift litt på fargene i ProgramCardsView
