### ISSUE TITLE
[BUG] Register bug when pushing Robot outside of map

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#144]
Hvis man dytter en Robot utenfor brettet før man starter spillet (ved bruk av piltastene), så krasjer spillet og man får følgende feilmelding:
```
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Number of cards do not match number of available slots in registers
```

**Comment by adipid** [comment]
**FYI**: Samme skjer hvis man trykker/kommer borti <kbd>ENTER</kbd> i mens en runde kjører 😅

**Comment by thomashusebo** [comment]
Denne feilmeldingen kommer i den situasjonen bare hvis du har brukt piltastene til å flytte roboten utenfor kartet e.g. du har ikke fulgt spillets regler. 

Hvis du bruker kort til å bevege deg, så skjer ikke dette.

**Comment by adipid** [comment]
Burde vel ikke lukke denne før det er lagt til en løsning for dette?

**Comment by thomashusebo** [comment]
Hm, Ok. Forslag til korrekt måte å håndtere det på? For dette faller utenfor reglene til spillet
