### ISSUE TITLE
[Robot] Take damage when pushed

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#146]
Man skal ta skade når en `Robot` dytter en annen, dette gjøres i `robotNextToRobot()`.

**Comment by buzzdead** [comment]
Hvordan kom du fram til denne regelen ? 
Var opprinnelig slik jeg implementerte det, men dere rettet meg og sa at man ikke skal ta skade når man blir dyttet av en annen robot, står ikke at man tar skade når man blir dyttet av en annen robot i regelboka så vidt jeg vet?

**Comment by adipid** [comment]
Reglene tilsier at man ikke tar skade, så her har jeg husket feil og misforstått 😅

![Skjermbilde 2020-04-22 kl  09 41 08](https://user-images.githubusercontent.com/5453010/79954272-65af7f00-847d-11ea-860d-c27650ab3ef1.png)
