### ISSUE TITLE
[BUG] The way cards are handled in the register class.

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#149]
Uten at jeg har satt meg for nøye inn i det så oppstår det problemer når man prøver å kjøre dette i et rundesystem med AI. Når man har 3 i helse og har 2 kort man skal spille med oppdaget jeg at registeret fant 1 kort som `getNumberOfCardsInRegister()`, men i virkeligheten så hadde man to kort. For å bugfixe dette så kan det være lurt å integrere det som skal til fra registeret inn i test `Phase` \ `Round` funksjonen og prøve seg litt fram. Prøv å skyt ned robotene til en lav helse og trykk enter for å starte en ny runde for å se de samme feilene jeg oppdaget.

Foreslår at vi er forsiktig med hva vi merger fram til vi har en klar forståelse av hva som er hva, hvis vi ikke får fiksa dette register problemet i tide tror jeg vi må vurdere å droppe denne funksjonaliteten da vi i praksis har et fungerende spill uten dette register systemet (her med en kø som fungerer akkurat likt i praksis). Nå er det vel heldigvis lett å ekskludere denne delen av spillet da vi har branches som foreløpig ikke bruker registeret.

Må si det var en god idé, det kunne hatt praktiske fordeler å hatt et register system, men om man ikke handler med omhu ved det man integrerer inn i prosjektet og verifiserer ett hundre prosent at absolutt all funksjonalitet er på plass så kan man ikke forvente at det skal bli tatt med som en seriøs del av prosjektet.

**Comment by adipid** [comment]
Register er allerede merga i develop, så her må vi ev. bare fikse problemet.

**Comment by buzzdead** [comment]
Er vel ikke så utrolig mye som er integrert inn i develop egentlig annet enn timer klassen, hva programcardsview angår så har vel du fortsatt det som er implementert i ui branchen. Når det kommer til å fikse problemet så er det et par ting å ta i betraktning. Akkurat nå har vi ikke muligheten til å se hvordan de andre delene vi har jobbet med fungerer sammen: ui, timer, ai, dette siden register står i veien for å kunne gå videre på en fornuftig måte. Kanskje er det mulig å kommentere til side den delen som bruker registeret inntil en eventuell fiks fra den som er ansvarlig, og til slutt slette det hvis det ikke går an å bruke det.

**Comment by adipid** [comment]
UI-elements er merga inn i develop også, det som ligger i UI-branchen nå er bare finjusteringer og slikt. Det er jo en del som allerede er merget.

Og vi kan lett se hvordan de ulike delene vi har fungerer sammen, det er bare å lage en ny lokal branch og teste. Du kan ikke bare si at vi må fryse prosjektet, vi må heller finne en løsning på problemet.

**Comment by adipid** [comment]
# For å reprodusere feilene
## Test 1
1. Få din `Robot` til å bare ha 2 **hp**
2. Prøv å spill ved <kbd>ENTER</kbd>
    - Man kan ikke trykke **DONE** etter å ha valgt kort
    - Og spillet krasjer

## Test 2
1. Dytt en vilkårlig `Robot` utenfor brettet
2. Trykk <kbd>ENTER</kbd>
    - Spillet vil krasje

**Comment by buzzdead** [comment]
Bra pusha.

**Comment by adipid** [comment]
Når jeg tester spillet nå, så fungerer alt som det skal så lenge jeg spiller spillet og ikke bruker `debugControls()` for å ta skade. Da klarer jeg ikke å reprodusere feilene.

Så jeg tror det ikke er så farlig alikevel, vi trenger nok bare finjustere at `Register` blir oppdatert når vi tester manuelt ved å **debugge**.

**Comment by buzzdead** [comment]
Nei

**Comment by adipid** [comment]
@buzzdead, oppdager du feilen(e) når du bare spiller ved å bruke <kbd>ENTER</kbd>?

**Comment by buzzdead** [comment]
Ja.. registeret er swiss cheese. Hvis man ønsker å virkelig teste det kan man egentlig bare lage en key bind til run round, og kjøre T-T-T-T-T også end round, da følger man manisk det systemet spillet følger.

**Comment by adipid** [comment]
Aha, du skulle jo bare sagt det med en gang.

**Comment by buzzdead** [comment]
Hvis du ser i toppen av issuet så sa jeg det med en gang.

**Comment by adipid** [comment]
Du skrev 3 mellomlange avsnitt, ingen av dem var så godt oppsummert som den siste der. 

Jeg kan begynne å se på dette i morgen, med et lite håp om jeg kan få @thomashusebo med siden det er han som har laget dette.

**Comment by adipid** [comment]
Den ene buggen skjer når en `Robot` dør, da kjøres i `register.add(-1)`, så natruligvis så krasjer spillet da.

**Comment by adipid** [comment]
Tror jeg fikset det:
```java
private int getNumberOfCardsToDraw() {
        if (getHealth() <= 0) {
            addHealth(SettingsUtil.ROBOT_MAX_HEALTH);
        }
        int numberOfCardsToDraw = getHealth() - 1; // For damage tokens, see rulebook page 9
        System.out.println(getName() + " numberOfCardsToDraw: " + numberOfCardsToDraw);
        return Math.max(0, numberOfCardsToDraw);
}
```
Setter bare helsen til `Robot` til fullt dersom den er lik eller mindre enn 0, da det er dette som gir feilmeldingen ut i fra hvordan jeg forstår problemet.

Etter jeg gjorde dette, klarer jeg ikke å produsere feilene igjen, selv med hva @buzzdead skrev:
> ... bare lage en key bind til run round, og kjøre T-T-T-T-T også end round, da følger man manisk det systemet spillet følger.

**Comment by adipid** [comment]
@buzzdead, prøv å merge med [ui](https://github.com/inf112-v20/crawling-crow/tree/ui) nå, da denne har alle de nyeste endringene og har alt av UI'en på plass.

**Comment by buzzdead** [comment]
Skal prøve det ut.

**Comment by buzzdead** [comment]
Exception in thread "LWJGL Application" java.lang.IllegalStateException: Number of cards do not match number of available slots in registers
	at roborally.game.cards.Register.add(Register.java:42)
	at roborally.game.gameboard.objects.robot.RobotLogic.fillFirstCardsFromHandIntoRegister(RobotLogic.java:197)
	at roborally.game.gameboard.objects.robot.RobotLogic.autoArrangeCardsInHand(RobotLogic.java:180)
	at roborally.game.Game.dealCards(Game.java:177)
	at roborally.ui.UI.keyUp(UI.java:153)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:325)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

Process finished with exit code 0

**Comment by buzzdead** [comment]
Føler ikke at å adde masse health til en robot fordi den skal trekke et kort er en god løsning uansett..

**Comment by adipid** [comment]
Kan du heller ikke være litt mer behjelpelig? Vi har ikke så mye arbeid igjen, eneste som gjenstår er AI og PowerDown, så skjønner ikke hvorfor du er så negativ til dette. 

- Hva gjorde du før det krasjet?
- Kan du lage en "oppskrift", så jeg kan prøve å reprodusere problemet?
- Lim inn hele feilmeldingen du fikk, er du snill.

**Comment by buzzdead** [comment]
Ikke mye arbeid igjen du liksom, det kommer jo an på hvor mye arbeid man har lyst til å gjøre det. Er utrolig masse ekstra man kan gjøre for eksempel, så vel som masse refaktorering som gjør prosjektet mye mer stilfullt og åpent for videre implementering, og dette er bare toppen av kransekaka. Det er utrolig kjett når ikke prosjektet blir tatt seriøst og man bare slenger inn kode uten å teste det mest åpenbare og elementære rundt det man implementerer, særlig når det er så nært kjernen til prosjektet som selve mekanikken man bruker til å faktisk spille spillet. Vet ikke hva feilmeldingen kom fra jeg, bare kjørte spillet noen runder.

**Comment by adipid** [comment]
Vi burde prøve å få fikset problemet, i stedenfor å være så negative til det. Vi har bare AI og Power down igjen.

Hvordan kan jeg reprodusere stegene du gjorde for å få samme feilmelding som du fikk?

**Comment by adipid** [comment]
Nettopp, ekstra. Vi må få plass fundamentet før vi legger på ekstra greier. Og jeg vet ikke med de andre, men jeg har tatt dette prosjektet seriøst fra første øyeblikk og du burde ikke si at noen andre ikke gjør det heller, selv om du mener det er sant, hold det for deg selv eller ta det opp med vedkommende.

At testene ikke har blitt gjennomført skikkelig er jeg jo enig i, men det er fort gjort og hvem som helst kan gjøre feil, inkludert deg selv. Du må gjerne prøve å gi tilbakemeldinger på pull requests i stedenfor å komme etterpå å si at det som er gjort er dårlig arbeid.

Når vi har på plass hele MVP'en kan vi refaktorere, og justere på koden. Men vi trenger ikke å henge oss opp i ekstra features før vi har fått på plass hele MVP'en.

**Comment by buzzdead** [comment]
Du kan mene hva du vil, jeg er fortsatt grådig irritert over dette, føler dette ødelegger mye for prosjektet hvis vi skal havne i tumulter over dette og ikke gå videre med prosjektet.

**Comment by adipid** [comment]
Vi kan jo jobbe videre, ingenting stopper deg eller oss.

Hvis du er ferdig med din oppgave, så begynn på noe annet, eller prøv å løs dette problemet i stedenfor å jobbe mot oss.

Nå avslutter vi denne diskusjonen, og prøver å løse problemet.

**Comment by buzzdead** [comment]
Jeg klarer ikke å jobbe med et prosjekt jeg ikke føler blir tatt seriøst. Hvis det ikke er fikset til onsdag så  tar vi en avstemming om vi skal ha et spill med feil eller ikke.

**Comment by adipid** [comment]
Nå har jeg spilt gjennom 4-5 ganger, og har ikke opplevd noe krasj av noen som helst form.

@buzzdead, har du brukt computer-branchen sammen med ui (som inneholder register) eller har du gått frem på noen annen måte? Jeg kan gjerne prøve å bruke computer-branchen til å teste, så hvis du har nye endringer, så er det fint om du pusher dem, så skal jeg prøve meg frem.

For akkurat nå klarer jeg ikke reprodusere problemene ved å faktisk spille spillet.

**Comment by adipid** [comment]
Lukker denne siden er litt diskusjon som ikke omhandler selve issuen.

Har laget en ny som har en grei oversikt #150
