### ISSUE TITLE
[UI] Win message

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#151]
En melding om at en `Robot` har vunnet.

**Comment by buzzdead** [comment]
Hadde vært bedre med game.endGame() istedenfor gdx.app.exit i exitButton, men man må forrandre litt på pause systemet i gameview ser jeg for at det skal funke som det skal.

**Comment by adipid** [comment]
Helt sant, det er veldig enkelt å endre knappene til å gjøre hva vi vil 😄

**Comment by buzzdead** [comment]
Kan lage en boolsk variabel wonGame elns i events og sette spillet tilbake til menyen om den er aktiv. Da kan man kjøre game.endGame og events.setWonGame i exitbutton, så fungerer det.

**Comment by adipid** [comment]
Dette er en implentasjonsdetalj, så et ikke så viktig i dette issuet sin sammenheng vil sei påstå 😅.

Trenger bare at noen ser på min pull request og sier det er good eller bad, og så går vi videre der i fra. Så får vi lukket litt flere saker, og jeg kan begynne å se på andre saker 😄
