### ISSUE TITLE
Som <spiller> trenger jeg <å kunne skrive navnet mitt> for <å vite hvilken robot jeg styrer>

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#161]
## Akseptansekriterier
- [x] Man har muligheten til å skrive inn navnet sitt før spillet begynner
- [x] Man får et default navn om man ikke overskriver navnet til roboten.

## Definisjonen av ferdig
- [x] Navnet til roboten er synlig på spillet.
- [x] #153

## Fint å ha
- [ ] En liste som oppdaterer seg om man slår en av de tidligere rekordene i spillet.

**Comment by buzzdead** [comment]
@adipid Hvordan har du tenkt til å ha synligheten til spillerene i forhold til dette? (UI-elements)

**Comment by adipid** [comment]
Jeg har ikke lagt noen plan for dette for øyeblikket, egentlig.

**Comment by buzzdead** [comment]
Er det ikke mulig å ha det som en del av UI elementene som viser spillerene med flagg osv?

**Comment by adipid** [comment]
Joda, det skal ikke være noe problem!

**Comment by buzzdead** [comment]
Burde være mulig i prinsippet å lage en leadingboard klasse som i hovedsak tar for seg ett texture og en robot, og instansiere denne klassen for hver robot. Dele opp bildene og oppdatere bildet etter hvor mange flagg roboten har tatt, mens labelen med navnet bare blir den samme.

**Comment by adipid** [comment]
> Burde være mulig i prinsippet å lage en leadingboard klasse som i hovedsak tar for seg ett texture og en robot, og instansiere denne klassen for hver robot. Dele opp bildene og oppdatere bildet etter hvor mange flagg roboten har tatt, mens labelen med navnet bare blir den samme.

Dette blir en ny User Story og ny arbeidsoppgave i så fall, dette går ikke direkte under det samme.
