### ISSUE TITLE
[UI] Visual feedback to user when interacting with game

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#163]
- [x] Vinne melding #151 
- [x] Når man besøker flagg
- [x] Når man dør
- [x] Når man faller i hull

**Comment by adipid** [comment]
Trenger litt flere finjusteringer før jeg sier meg ferdig med denne, men alle meldingene fungerer nå :) 

La også til flagg i UI #165

**Comment by buzzdead** [comment]
Forslag til debugging:
1. Stell en robot ved siden av et flag, stå ved siden av roboten, bruk et move 2 eller move 3 kort og se hva som skjer.
2. Stell en robot ved siden av ett flag, stå ved siden av roboten, bruke et move 1 kort, så et annet move 1 kort, se hva som skjer.
3. Helst styre 2 roboter. Få en robot som har besøkt flagg 1 til å besøke flagg 2 samme runde som du besøker flagg 1 osv. Beste er nok å lage tester for ui messages for fortgang på dette.

**Comment by adipid** [comment]
> Forslag til debugging:
> 
>     1. Stell en robot ved siden av et flag, stå ved siden av roboten, bruk et move 2 eller move 3 kort og se hva som skjer.
> 
>     2. Stell en robot ved siden av ett flag, stå ved siden av roboten, bruke et move 1 kort, så et annet move 1 kort, se hva som skjer.
> 
>     3. Helst styre 2 roboter. Få en robot som har besøkt flagg 1 til å besøke flagg 2 samme runde som du besøker flagg 1 osv. Beste er nok å lage tester for ui messages for fortgang på dette. Da lage en logikk som ikke er avhengig av noe som helst UI elns som man kan lage test class av.

Skjønner ikke helt hva dette har med dette issue å gjøre, men det skjer ingenting spesielt når man gjør dette, se GIF'ene:

# 1
![Skjermopptak 2020-04-30 kl  16 34 46](https://user-images.githubusercontent.com/5453010/80725217-0f88ae80-8b03-11ea-9129-d43a0686dec9.gif)

# 2
![Skjermopptak 2020-04-30 kl  16 39 50](https://user-images.githubusercontent.com/5453010/80725419-54ace080-8b03-11ea-9e15-67b53090866e.gif)

# 3
![Skjermopptak 2020-04-30 kl  16 36 29](https://user-images.githubusercontent.com/5453010/80725572-8b82f680-8b03-11ea-947a-565fef97a43e.gif)

**Comment by buzzdead** [comment]
Hmm, vet ikke om du har prøvd det jeg mente, men hvis du går ut ifra den siste gifen, og roboten din hadde pekt mot den grønne, og du hadde brukt move 3 kort eller move 1 move 1... Tror jeg fikk noe bug da.

**Comment by adipid** [comment]
Jeg gjorde det som du sa, bortsett fra å legge til 2-player (for å si det enkelt), og jeg ser fremdeles ikke hva dette har med dette issuet å gjøre.

Se siste GIF, da gjør jeg igjen som du sier:
![Skjermopptak 2020-04-30 kl  17 17 11](https://user-images.githubusercontent.com/5453010/80728047-c6d2f480-8b06-11ea-9be0-7ce6177085be.gif)

**Comment by buzzdead** [comment]
Hmm, mulig jeg tok feil! :)
Skal man ikke ha muligheten til å se om de andre robotene besøker flagg da?

**Comment by adipid** [comment]
> Skal man ikke ha muligheten til å se om de andre robotene besøker flagg da?

Det er jo et godt poeng, akkurat sånn jeg har gjort det nå så får du ikke direkte beskjed om det, men det kan jeg enkelt ordne! :)

**Comment by adipid** [comment]
Det eneste som mangler nå, er at spillet stopper når noen vinner.
