### ISSUE TITLE
[BUG] [UI] Some UI elements (when resizing) are not reacting to input when clicked on

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#166]
Noen UI elementer reagerer ikke riktig når man klikker på dem, man er nødt til å klikke litt til siden av dem.

- Dette skjer alltid på macOS hvis man har lavere oppløsning eller skalert OS'et lavere enn 1080p.
- Forekommer også på WIndows når man resizer en del.

**Comment by buzzdead** [comment]
Teste på forskjellige oppløsninger, gjerne på TV osv før man til slutt closer denne?
Stort sett bør det være ok å teste på PC så er vel ikke så utrolig nøye.

**Comment by adipid** [comment]
Har testet på min store PC skjerm med 2560x2440 og satt MacBooken til 2048x1280, det er en god del høyere enn 1920x1080 og det funkerte kjempebra! 

Men når jeg testet å nedskalere MacBooken til 1280x720, så ser UI'en veldig stor ut. Problemet på macOS er at man ikke får lov å ha større vindu enn hva oppløsningen tilsier, og jeg mener det ikke er en begrensning på Windows.

<img width="1152" alt="Skjermbilde 2020-04-30 kl  14 10 32" src="https://user-images.githubusercontent.com/5453010/80708684-5f0fb000-8aec-11ea-9d48-6bad7abe2616.png">

Så jeg lurer på om dette er noe vi burde spør Fromsa om mtp om vi skal kunne støtte Mac med lav oppløsning, for det er kun her jeg tror det blir et problem.

**Comment by adipid** [comment]
Tror jeg har en fix på det overnevnte problemet, er ikke hjemme akkurat nå, men skal prøve å få testa fixen senere i dag

**Comment by adipid** [comment]
> Tror jeg har en fix på det overnevnte problemet, er ikke hjemme akkurat nå, men skal prøve å få testa fixen senere i dag

Nei, det funka ikke alikevel, resten av UI'en følgte ikke med, så det ble ikke resizet som jeg hadde ønsket :(

**Comment by buzzdead** [comment]
Om problemet bare er at UIen ser stor ut så er ikke det noe problem.

**Comment by adipid** [comment]
> Om problemet bare er at UIen ser stor ut så er ikke det noe problem.

Har du en fiks på det da ev.? For fiksen er relativt enkel, linje 79 i `GameView`
```java
camera.setToOrtho(false, SettingsUtil.WINDOW_WIDTH, SettingsUtil.WINDOW_HEIGHT);
```

**Comment by buzzdead** [comment]
Denne vi implementerte var det ikke? Jeg trodde du mente at UI elementene ble store på mac med lav oppløsning -etter- denne fiksen?

**Comment by adipid** [comment]
Dette er en endring, egentlig så står det 
```java
camera.setToOrtho(false, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
```

Det vi endra på tidligere var `FitViewport()`. Skjønner det ser veldig likt ut 😅

**Comment by buzzdead** [comment]
Hmmm, så lenge det ikke forrandrer på noe annet så er det vel bare å skifte den da hvis den fikser mac med lav res også?

**Comment by adipid** [comment]
Den fikser mac med lav res, men lager et nytt problem siden UI'en skalerer ikke på samme nivå...

<img width="1152" alt="Skjermbilde 2020-04-30 kl  18 07 03" src="https://user-images.githubusercontent.com/5453010/80733074-7f9c3200-8b0d-11ea-9f37-298a8c2fef38.png">

**Comment by buzzdead** [comment]
Vurdere å lage en mac med lav res option da i menyen.

**Comment by adipid** [comment]
Jupp, med mindre Fromsa sier vi ikke trenger å tenke på det.

**Comment by adipid** [comment]
Kom over en tilfeldig ting;
Hvis man setter `cfg.useHDPI = true` i `Main`, så forsvinner problemet på moderne maskiner som skalerer pga høy oppløsning, men det skaper nye problemer igjen, se bilde.
<img width="1792" alt="Skjermbilde 2020-05-08 kl  01 08 15" src="https://user-images.githubusercontent.com/5453010/81353062-67598380-90c8-11ea-8246-f12469dfef37.png">

Var helt tilfeldig at jeg kom over dette, har ikke planer om å fikse dette.
