### ISSUE TITLE
[UI] Background

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#172]
Som del av UI så må vi implementere en bakgrunn også. #116
Har laget en branch med et utkast på dette kalt ui/background, hvor jeg bare satt opp 2 "bars", vertikal og horisontal, og tegner de på hver side av mappet.. Fungerer ganske fint, men om man har lyst på et fullstendig mønster man nødt til å skjøte de opp som fire bilder til et stort bilde som på en måte omfavner mappet, vet ikke om det fungerer i praksis med hensyn på resize men kanskje. 
Når det er sagt så står man fritt til å forrandre på utseendet på disse barsene, bare slenge de inn i en eller annen editor og endre mønster og erstatte filene Untitled og Untitled2.png.

**Comment by adipid** [comment]
Dette er ikke noe vi MÅ ha, helt ærlig synes jeg ikke vi trenger bakgrunn.

Dette er noe som alle i gruppen heller kan bli enige om.

**Comment by buzzdead** [comment]
Det var nå en konsensus om å ha bakgrunn når vi gikk igjennom UI på gruppemøtet, så tror vi kjører bakgrunn på bakgrunn av det. Har implementert det så er bare å legge til etter litt finjusteringer bare.

**Comment by adipid** [comment]
Fremdeles mener jeg at alle skal få ha en mening om dette, for ingen har sagt at vi MÅ ha bakgrunn enda. Det er kjekkest hvis alle er enig.

**Comment by buzzdead** [comment]
Hehe, det var ingen som hadde en mening om noe som helst av hva vi har av UI, vi gikk igjennom dette på møtet og de fleste var om bord på det som ble tatt opp på møtet, hvor bakgrunn var endel av det. Hvis du har lyst til å gå tilbake til ting vi allerede har vært igjennnom så føler jeg det blir litt uproduktivt, skal vi alle begynne å kalle avstemming om ting vi ikke personlig liker?

**Comment by adipid** [comment]
Det var ikke sånt ment, sorry. Mente bare at ingen har tatt det opp igjen før nå.

Det er enda enklere måte å gjøre det på en hva du har gjort til nå, det er bare å rendre bakgrunnen før man rendrer brettet. Se siste oppdatering i branchen din, 3a96dfc0be7b13a842ec95bfc94a61d9710aacf0. Dette gjør at man slipper å dele bilde opp i biter osv.

**Comment by adipid** [comment]
Brukte forresten bakgrunnsbilde vi ble enige om på første møte også :)

**Comment by buzzdead** [comment]
Ja skjønner ikke hvorfor dette er så stor sak, hvis man er uenig om hvordan bakgrunnen er så har man som utvikler rett til å sette sin egen bakgrunn til sitt eget map. Bedre å ha en egen bakgrunn enn å bruke den som er satt til default i vinduet til libgdx.

**Comment by adipid** [comment]
Selvfølgelig, jeg mente det ikke sånn Sigmund. Det var ikke sånn at jeg mente at vi ikke kunne ha en bakgrunn (jeg ga min personlige mening), og nå ser jeg hvor enkelt det var å legge til og det er veldig enkelt å endre bakgrunnen til akkurat det vi har lyst til. Og det ser fremdeles veldig bra ut :)

**Comment by adipid** [comment]
@buzzdead, fikk du sett på endringen jeg gjorde?

**Comment by buzzdead** [comment]
Ja, prøvde å gjøre det sånn selv men jeg tegnet det i starten av render og ikke etter linje 130 så det ble ikke registrert. Samme hvilken måte man gjør det på så ender man opp med svarte linjer på venstre og høyre side, vet ikke om det er sånn for alle oppløsninger. Vel, jeg hadde allerede implementert det? Kanskje ikke noe poeng å sette seg opp mot det da...

**Comment by buzzdead** [comment]
Videre implementasjon her kan vi legge til at man enten velger bakgrunn i det man velger map, eller at  vi setter bakgrunn til de forskjellige mappene hvis vi ønsker det, jeg har forsåvidt lyst til å legge til min egen bakgrunn på et map.

**Comment by adipid** [comment]
Det kommer av størrelsen på bilde. Det kan være veldig upraktisk å måtte dele opp bilde hvis vi skal endre bakgrunnsbilde senere. Jeg kan gjøre bakgrunnsbilde til 16:9 format, da vil det fungere fint på alle vanlige widescreen skjermer. (Jeg bare la inn bilde uten å endre på det full fart).

Å bare måtte endre 1 fil tar mye mindre tid enn å endre 2.

Men hvis du vil gjøre det sånn, så skal jeg ikke si noe, men bruk det bilde vi hvert fall ble enige om alle sammen til hovedbrettet som vi har brukt en stund nå. Så kan vi heller bli enige om noe annet senere.

**Comment by buzzdead** [comment]
Hmm, tror ikke det er det som avgjør det nei. Når man tegner et bilde uten å sette noe posisjon så tegner man fra pixel 0,0.. altså nederst til venstre i rommet hvor det er mulig å i det hele tatt tegne, men det blir ikke helt til venstre på programmet, men litt forskyvet til høyre, samme på høyre side.. lurer på om problemet ligger enten i libgdx selv, eller hvordan vi lager cameraet.

Ja er ikke noe problem å hente bilde fra menyen i forhold til hvilket map det er. Kan godt bruke det bildet på hovedmapet om Lise ønsker det, tross alt hun som lagde mapet ;)

**Comment by adipid** [comment]
Det er ingen svarte linjer her. Ser det blir det hvis man resizer ned.
![Skjermbilde 2020-05-01 kl  11 51 12](https://user-images.githubusercontent.com/5453010/80797411-10245200-8ba2-11ea-9dba-8b7e44682d8c.png)

**Comment by buzzdead** [comment]
Da er det resize som er problemet. Er ikke så nøye hvis det fungerer fint på de fleste skjermer, er ikke akkurat noe man legger særlig merke til.

**Comment by buzzdead** [comment]
Da har jeg ordnet dette, om man ønsker egen bakgrunn til et map man lager så er det bare å legge det til på lik måte.
