### ISSUE TITLE
[UI] Leaderboard

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#173]
Lagde et utkast for LeaderBoard som kan jobbes med i ui/leaderboard branchen. #116
Kanskje kan man tegne det enkelte bilde for hver robot i samme posisjon som man ser der (fremfor hele leaderboard teksturen), da ser man ganske klart hvilke robot(er) som ligger først osv.
Kan man ha hvilke roboter som spiller hvilke kort på høyre siden kanskje..
Ganske enkel måte å gjøre det ved å legge til stringnavnet til det respektive bildet til enhver robot i forhold til navnet på roboten, man kan bare lage en egen metode for userRobot.
Fordelen med denne metoden blir at man i tillegg til å velge navn også kan velge farge på roboten man tar.

**Comment by buzzdead** [comment]
Vært fint om dere kunne tatt en kikk og gitt reply hva dere synes om denne måten å håndtere leaderboard på, kan selvfølgelig også ha det slik som det vises i UI issuet med at bildet til robotens leaderboard alltid er klammet til venstre siden for mappet... synes det var mer oversiktelig slik som det er nå på en måte, men på en annen måte så blir det også litt hulter til bulter, en annen grunn til at jeg liker det sånn det er nå er at man kan introdusere reaperrobot, men jeg vet ikke om det blir noe av jeg.

**Comment by buzzdead** [comment]
Som sagt best testet på mappet "Eight" med conveyorbelts rundt hele mappet, bare spille random kort med fast modes.

**Comment by adipid** [comment]
Ser bra ut!

**Comment by buzzdead** [comment]
Denne er nå lagt inn for review til å pulles inn i develop, hvis noen har lyst til å gjøre litt forrandringer så er tiden nå! :)
