### ISSUE TITLE
[BUG] Cards played and cards in register diverge.

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#174]
Vet ikke om det er pga cards arrayet i register eller hva det er.
Men hvis en robot som du ikke styrer selv har mindre enn 6 hp og dermed en order[] og et register[] (newcardstoregister[]) som er mindre enn 5, så spiller den fortsatt 5 kort... 

En fiks til dette problemet vil være å legge til kortene som roboten skal spille i en kø igjen og bruke de kortene til å spille spillet med. Register kan forsåvidt være som det er da det er i bruk andre steder, men så lenge det ikke fungerer så må vi bare kutte tapene våre her.

Og skal man virkelig bugteste det her så tror jeg det er fornuftig å lage en egen branch, og kommentere vekk absolutt alt med System.out.print foran. Legge til printout for newregister arrayet i robotlogic så ser man hvilke kort som blir lagt til i registeret, (spes da robotene har lav hp) og verifisere at det er noen få kort som blir lagt til, også ser man at roboten spiller flere kort.

Kan bekrefte at helsesystemet i Leaderboard branchen fungerer som det skal så den helsen du ser som oppdaterer seg over leaderboard uiet til roboten faktisk er helsen til roboten, kan verifisere at ai fungerer som den skal i forhold til størrelse på listen med kort, kan forsåvidt like greit bruke autoarrange for å bugteste. (Linje 162 og 163 i Game.Java).

**Comment by buzzdead** [comment]
Kanskje lettest å se i leaderboard branchen da jeg har lagt til synlig HP for hver robot der..
Keep in mind det er ikke helt ferdig så etter man har trykket på start game så må man lukke spillet å starte igjen hvis man skal restarte det på en måte.

**Comment by buzzdead** [comment]
Gjelder forsåvidt roboten man selv styrer også.. Vet ikke hva som er blitt forrandret men må ha vært nå nylig?

**Comment by buzzdead** [comment]
Virker som de til tider spiller kort i f.eks fase 1, 2, 3, også skipper 4, også spiller i fase 5.. ganske rart hele problemet, tror kanskje den fiksen som ble gjort for Register klassen ikke er helt i mål.

**Comment by adipid** [comment]
> Gjelder forsåvidt roboten man selv styrer også.. Vet ikke hva som er blitt forrandret men må ha vært nå nylig?

Det kan faktisk komme av den endringen jeg gjorde med at man slipper å vente på timer i powerdown eller når man er tom for kort.

Jeg skal få sett på dette imorgen

**Comment by buzzdead** [comment]
Tror ikke det er det, fordi det gjelder ikke bare roboten man selv styrer, og det gjelder uavhengig av powerdown, og man trenger ikke være tom for kort.

**Comment by adipid** [comment]
Feilen er der også når @thomashusebo og jeg trodde vi hadde løst alle problemene med `Register`-klassen. 
Framprovoserte buggen i 1077b716532ef52b40548941ccd867c774ffe2ff

**Comment by buzzdead** [comment]
Viktigheten av visuell feedback for alt som er relevant når man bugtester noe grafisk er ikke å undervurdere, oppdaget dette øyeblikkelig i leaderboard branchen.

**Comment by thomashusebo** [comment]
"Men hvis en robot som du ikke styrer selv har mindre enn 6 hp og dermed en order[] og et register[] (newcardstoregister[]) som er mindre enn 5, så spiller den fortsatt 5 kort..."

Hva er feil?

**Comment by buzzdead** [comment]
Hvis du har mindre enn 6 hp så skal du ikke spille 5 kort...

**Comment by thomashusebo** [comment]
Joda. Man skal alltid spille 5 kort fra registeret. 
Et register er alltid fullt og du skal spille alle kort fra register hver runde.

Man får hver runde derimot bare lov å oppdatere de registerene som ikke er låst. Men selv et låst register har et kort i seg.

**Comment by buzzdead** [comment]
Hva i alle dager er det du snakker om?
Hvis du har 3 helse, hvor mange kort skal du spille, og i hvilke faser?

**Comment by thomashusebo** [comment]
Kan ta et hypotetisk spill. 
RUNDE 1:
- Alle har full hp => Alle har 10 kort => Alle fyller opp sitt register
- La oss si at Blue valge kortene: [MOVE1, MOVE2, MOVE3, ROTATE_LEFT, ROTATE_RIGHT]
- La oss si at Blue tar 7 skade, og har 3 helse igjen
- Da låses 3 kort i Blue sitt register. (altså de tre siste)
- Blue sitt register er da på slutten av runden: [tomt, tomt, MOVE3, ROTATE_LEFT, ROTATE_RIGHT] (altså 3 låste registre)

RUNDE 2: 
- Blue får 2 kort, siden han har 3 hp: [BACK_UP, BACK_UP]
- Disse to kortene plasserer Blue i sin register, på de to ledige plassene.
- Blue sitt nye register blir da: [BACK_UP, BACK_UP, MOVE3, ROTATE_LEFT, ROTATE_RIGHT]
- Kortene blir spilt i den rekkefølgen de er i registeret.

**Comment by thomashusebo** [comment]
Dette er ikke en bug, men en misforståelse av reglene :)

**Comment by buzzdead** [comment]
Hvorfor forklarte du ikke det her tidligere?

**Comment by thomashusebo** [comment]
Fordi det er helg

**Comment by buzzdead** [comment]
Jeg mener da du implmeneterte Register klassen, jeg hadde tydeligvis misforstått reglene ved å bruke bare en kø..

**Comment by buzzdead** [comment]
Ikke close det da? Betyr ikke at det fungerer som det skal.

**Comment by buzzdead** [comment]
I spillet så spiller blue 5 kort med 2 helse, du kan ikke mene at det er riktig i forhold til reglene?

**Comment by thomashusebo** [comment]
I såfall må du definere hva du mener med å "spille 5 kort". Hvis blue har 5 kort på hånden, så er det feil. Hvis blue har 5 kort i registeret, så er det rett

**Comment by adipid** [comment]
![Skjermbilde 2020-05-03 kl  16 20 30](https://user-images.githubusercontent.com/5453010/80916599-047b8b80-8d5a-11ea-95ca-928249878657.png)

**Comment by thomashusebo** [comment]
> I spillet så spiller blue 5 kort med 2 helse, du kan ikke mene at det er riktig i forhold til reglene?
> Skal man alltid spille 5 kort, bare at man bruker de låste kortene hver runde?

Ja. Man spiller de låste kortene. Mener Sib kalte det "glitching" i ene forelesning

**Comment by buzzdead** [comment]
Ja slik jeg tolker reglene nå også, har aldri lest det avsnittet før.
Utrolig leit at ingen har nevnt noe om dette i forbindelse med overgangen fra kø til register..

**Comment by adipid** [comment]
Alle har vel et eget ansvar med å lese reglene. Skal ikke påstå at jeg visste dette heller, men det er rett som @thomashusebo sier.
