### ISSUE TITLE
[Menu] Choose menu background

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#176]
Vi har for tiden 2 bakgrunns bilder til menyen, men bruker kun en av de.
Jeg setter opp 3 valg her, så kan dere reagere med tommel opp om dere ønsker å bruke den vi for tiden bruker, eller tommel ned hvis dere ønsker å bruke den gamle bakgrunnen til menyen. 
Å ikke stemme blir regnet som om at man ønsker å bli enige om en ny bakgrunn til menyen.

Man kan se bakgrunnene jeg snakker om i assets/menu
new-menu er den vi bruker  nå, menu er den vi brukte tidligere.

**Comment by adipid** [comment]
Stemmer for å ikke priortere dette nå, vi kan godt bare bruke de bakgrunnen vi har nå 😄

**Comment by buzzdead** [comment]
Så stem på den bakgrunnen du vil ha da?

**Comment by adipid** [comment]
Vi kan ha alle for min del, går helt fint, jeg bryr meg ikke :)

**Comment by buzzdead** [comment]
Det er bare 2 meny bakgrunner å velge mellom, skulle tro du hadde en mening om hvilken du vil ha da du lagde en ny meny som følge av den førstkommende menyen som ble satt inn i spillet.

**Comment by buzzdead** [comment]
Med mindre noen kommer med noen gode idéer så bruker vi den menyen vi for tiden har. Closer den for nå.
