### ISSUE TITLE
Finalize the game

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#179]
- [x] Fullføre alle issues markert med MVP og BUG, og til slutt fullføre spillet i henhold til #72 .
Definisjon av ferdig:
Spillet startes ved oppstart og kjøres til en spiller vinner spillet, uten behov for å trykke på knapper på tastaturet.

- [x] For å virkelig gjøre ferdig spillet så følger så mange som mulig av andre issues (nice to have, enhancement osv..) og ikke minst #162 , først da er vi ferdig med spillet!
Definisjon av ferdig: 
Spillet ser kjempe bra ut både utvendig og innvendig!

**Comment by thomashusebo** [comment]
Jeg prøver å gjøre runder automatisk, men uten å fjerne muligheten for å bruke debug kontrollere. Se egen branch (automatedRounds)
