### ISSUE TITLE
Use of region and endregion in our program

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#180]
Siden vi ikke er så flinke med kommentarer og for fortgang i saken da tiden begynner å renne ut så håper jeg på en tommel opp om man ønsker å gjøre om dette til mer Java stil, eller en tommel ned om man ønsker å ha det som det er.

Region of endregion er stort sett noe som blir brukt i visual studio og c++. I c++ er det stort sett for å kunne utheve og kollapse et stykke kode, mens Java tilbyr ikke noe sånt. I Java så har man muligheten til å kollapse metoder og derfor så satser man heller på å gjøre metoder så korte som mulig og følge Single Responsibility Principle. Siden region og endregion ikke hjelper til noe annet enn å gjøre filene våre større og egentlig oppleves det mer tungvint å lese kode når det står region og endregion så synes jeg vi bør endre dette. For å skille mellom to deler så markerer man det gjerne med mellomrom, noe alle burde ha lett for å lese. Tommel opp for å erstatte region og endregion med bare "// Description" over, og mellomrom når denne regionen er over.

**Comment by adipid** [comment]
Det gjør jo bare koden enklere å lese, IntelliJ har dette innebygd for å gjøre det enklere å kollapse koden. Det er ingenting som tilsier at det er dårlig å ha **region**.

**Comment by buzzdead** [comment]
Gjør ikke koden lettere å lese spør du meg, er vel smak og behag hvor man kommer fra så vi får komme til enighet gjennom stemmer.

**Comment by adipid** [comment]
Det kan hjelpe for andre som ikke har sett koden før å få en oversikt hvor ulike ting er plassert i hver klasse. Men sant som du sier, er nok smak og behag.

**Comment by buzzdead** [comment]
Vel, ta en titt på #162 , det skal ikke være såkalte "ulike ting" i en klasse.

**Comment by adipid** [comment]
Med ulike ting, så mener jeg for eksempel slik som i Robot klassen. At en del av koden er for **movement**, annen del for **cards** osv.

**Comment by buzzdead** [comment]
Den bør refaktoreres, og movement bør egentlig være en egen klasse.
Når og hvis vi får strukturen på plass tror jeg det vil være mye lettere å lese koden, om man i det hele tatt skal ha noe beskrivelse er egentlig spørsmålet endel steder.
