### ISSUE TITLE
[BUG] Robot's Texture changes direction when dying

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#183]
Er ikke noe kritisk, men ser kanskje litt rart ut hvis man legger merke til det.

**Comment by buzzdead** [comment]
Ja når de fader? Har prøvd å tatt hensyn til det, problemet er at teksturen er 300 x 300, mens som tile så blir de redusert med tre 16-deler. 3 / 16. Når man da putter teksturen inn i et bilde og prøver å rotere det så blir det helt feil plassering, slik som jeg viste i forhold til når roboten detter ned i hull. Er nok ganske så sikkert en utvei for å fikse det, har bare ikke funnet ut av det enda.

**Comment by buzzdead** [comment]
Fikk ordna det for rotasjon, men tror jeg skipper å prøve å fikse den her da man må legge til enda en variabel i fadeRobot for direksjonen den er i, og jeg er ikke helt 100% sikker på åssen man skal gjøre det. Men du kan jo tenke deg i en film, terminator eller andre filmer med roboter, setter ikke robotene seg i sånn spesiell stilling som regel når noe spesielt skjer.
