### ISSUE TITLE
[BUG] Start new game - cleanup after previous game

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#189]
- [x] Det er ikke alltid at gamle roboter blir fjernet fra mappet. De blir av og til, men vet ikke hva som er avgjørende faktor her. 
- [x] Roboter får nytt navn når spillet startes på nytt til ex. "Blue nr 1". Er dette noe vi fortsatt ønsker?

**Comment by buzzdead** [comment]
Nei, nummerene til robotene var bare pga fun mode,
er ikke helt kjent med den første buggen.
