### ISSUE TITLE
Select between different gameboards

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#19]
Kunne velge mellom ulike predefinerte spillbrett.

**Comment by buzzdead** [comment]
Skal være veldig mulig det nå. Alt man trenger å gjøre er å lage et map og legge det til i AssManager forsåvidt, på samme måte som TEST_MAP som ligger der inne fra før.

**Comment by adipid** [comment]
Dette kan nå bli gjort via hovedmenyen.
