### ISSUE TITLE
[BUG] Texture sometimes not correct wrt. direction of robot

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#190]
Av og til, når man avslutter runden sin med et rotasjonskort, så vil den visuelle representasjonen av robotene "snu tilbake" til veien den så før den roterte. Når man da spiller neste kort, så roterer den korrekt i forhold til siste spilte kort, men ikke med hensyn til retningen som roboten peker.

**Comment by buzzdead** [comment]
Tar gjerne et visuelt eksempel på dette...

**Comment by buzzdead** [comment]
Så denne buggen i sted.. virket som den kom helt ut av det blå! Jeg lurer på om det kan ha med måten vi gjorde continuegameLoop på av alle ting, for det har ikke vært sånn før.

**Comment by buzzdead** [comment]
Eneste måten å debugge dette er om man klarer å force en printout akkurat når dette skjer, med så mye som mulig informasjon.

**Comment by buzzdead** [comment]
Om man åpner tiled map editor og brusher vekk alle startposisjoner bortsett fra 1 og prøver å spille spillet så virker det ikke som buggen oppstår.. kanskje er buggen et produkt av noe som henger igjen ved skifting av tekstur ved å ta damage?

**Comment by buzzdead** [comment]
Nesten sikker på at dette har med hitRobot i LaserEvent og at teksturen oppdateres ved at man tar damage i takeDamage i Robot som kaller på setdamagetakentexture... så må fikse det her

**Comment by buzzdead** [comment]
Denne buggen kom fra en pesky metode kalt restRobotTextures... Fryktelig!!! Lurer på om kanskje denne forårsaker problemene med at man plutselig kopierer opp en tekstur på kartet også faktisk! Foreslår at vi dropper den her, det er helt ok at en robot står i damage taken tekstur om den ikke har bevegd seg, selv om det er ny runde.
