### ISSUE TITLE
[BUG] Duplicate robots

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#191]
None ganger kommer det duplikat av en eksiterende robot. 

Jeg har bare sett duplikatet bli dannet på et reparasjonspunkt, og duplikatet roterer likt som den orginale roboten, men beveger seg ikke. 

Mulig det er en effekt av enten reboot på reparasjonspunkt eller kluss når mange roboter står på samme posisjon. 

![TwoYellowRobots](https://user-images.githubusercontent.com/45336748/80944687-6c79b280-8dea-11ea-9e3c-6fbfe12a1f7c.PNG)

**Comment by adipid** [comment]
Jeg opplevde akkurat det samme i explosions-branchen nå, det skjedde når eg kom tilbake til startpunktet. Når jeg prøvde å bevege meg, så kom det en duplikat som roterer likt, men flytter seg ikke.

**Comment by buzzdead** [comment]
Har allerede bug på dette #185
Tror problemet er når det er en robot går inn på et akriv punkt hvor det står en robot som er i virtual mode, ikke helt sikker.

**Comment by adipid** [comment]
Lukker siden denne er duplicate av #185

**Comment by buzzdead** [comment]
Ja, er samme problemet det er snakk om.
