### ISSUE TITLE
[BUG] Round aborted in a middle of a phase

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#192]
Noen ganger, så blir en runde avbrutt før alle kortene er blitt spilt. 

Har fått denne bugen 3-4 ganger men vet ikke hva som trigger den.

**Comment by buzzdead** [comment]
eKan dette ha med den skip greia @adipid lagde?

**Comment by buzzdead** [comment]
Eneste måten å debugge dette er om man klarer å force en printout akkurat når dette skjer, med så mye som mulig informasjon.

**Comment by thomashusebo** [comment]
Det er mulig at det skjer i forbindelse med restart av spillet. 
Når vi restarter så instansierer vi ikke spillobjektene på nytt, men heller oppdaterer de som var fra før. Det er mulig at dette er en konsekvens. Det skjer relativt ofte etter en restart.

**Comment by buzzdead** [comment]
Ja vet ikke jeg, ser nå ut som det meste blir tatt hånd om i restartGame.

**Comment by thomashusebo** [comment]
### Gjorde litt mer grundig bugtesting og begynner å se et mønster:

**Når skipper spillet over faser?** - Første runde etter restart.
**Hvor mange runder blir spilt før den avbryter?** - Avhengig av hvor mange kort som ble spilt i siste runde av spillet som ble avsluttet:

Spilte 1 kort fra avsluttet runde => Spiller 4 kort i første runde i nytt spill
Spilte 2 kort fra avsluttet runde => Spiller 2 kort i første runde i nytt spill
Spilte 3 kort fra avsluttet runde => Spiller 1 kort i første runde i nytt spill
Spilte 4 kort fra avsluttet runde => Spiller 0 kort i første runde i nytt spill

**Når man spiller 5 kort i siste runde har to ting skjedd.** 
- Enten så restarter vi før laser er ferdig å skyte (før cleanup):
    - da spilles 5 kort fra avsluttet runde => Spiller 0 kort i første runde i nytt spill

- Eller hvis man lar hele runden avslutte, med cleanup og alt, så skjer dette i neste spill:
    - Roboter blir ikke fjernet fra map (se bilde)
    - Legg forresten merke til at registeret ikke blir fjernet. Dette gjelder hver restart uansett. 

![image](https://user-images.githubusercontent.com/45336748/81270007-68e46680-904a-11ea-800a-c83251dcc34a.png)

**Comment by thomashusebo** [comment]
Kan nevne at innimellom, omtrent 15% av gangene, så blir ikke robotene redrawet på restart. Men hvis jeg restarter på nytt vil de komme til slutt. Selv om jeg restarter igjen, så er antall kort som blir spilt, avhengig av hvor mange kort som ble spilt på runden som ble avbrutt

**Comment by buzzdead** [comment]
Jeg ser sethasrestarted bør antakelig være siste som blir gjort i restartgame

**Comment by buzzdead** [comment]
Kan det være at registeret ikke blir clearet ordentlig i restart game? noe som ville vært annerledes enn fra start game

**Comment by thomashusebo** [comment]
Jeg antar at et nytt spill har nye roboter. Nye roboter har nye instanser av registre. 
Er mulig ui-representasjonen av register ikke blir fjernet på rett plass?
