### ISSUE TITLE
Create Class diagram

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#2]
As a part of exercise 1 we need to create a class diagram, which will be a part of our evaluation. 

I assume we should have this in our "Deliverables"-folder in github

Would except this document to change a lot during the semester, any good suggestions for how to create this document, to make it easy to modify later?

**Comment by buzzdead** [comment]
Uploading this for substance. Methods and attributes are of course due for refactoring.
<img width="365" alt="UML" src="https://user-images.githubusercontent.com/43996726/73863107-ddd3b480-483f-11ea-8383-82f24ed773ad.png">

**Comment by buzzdead** [comment]
![UML](https://user-images.githubusercontent.com/43996726/74036321-53648f80-49bc-11ea-8d83-755cf1fcd775.PNG)
