### ISSUE TITLE
Robot List

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#20]
Lage en liste med layers slik at vi kan ha flere roboter. 
Hvilke robot som skal gjøre noe er avhengig blant annet av prioritet på kortene de har, så vi blir nødt til å sette oss litt inn i dette for å implementere en robust struktur for hvordan vi finner ut hvilken robot som skal gjøre noe. Hva lagene angår tenker jeg at vi lager et HashMap med lagene til de forskjellige robotene, med robotnavnene som nøkkel! Er vel også mulig å ha alle robotene på ett lag, men det får vi finne ut av.

**Comment by adipid** [comment]
@buzzdead, status på denne?

**Comment by buzzdead** [comment]
La inn en kommentar når jeg refaktorerte graveyard funksjonen tidligere. Fortsatt aktuelt det issuet her, men er ikke helt klart hva slags kriterier eller hva slags funksjonalitet vi ønsker å forholde oss til her. Kanskje enten lage et nytt issue eller refaktorere issuet rett og slett.
[comment](https://github.com/inf112-v20/crawling-crow/commit/fe459d8b3f321829c1a60809bbf48259b032aa21#commitcomment-37878729)
