### ISSUE TITLE
[Wiki] UI explaination

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#203]
Oppdatere forklaringen på de ulike UI-elementene.
https://github.com/inf112-v20/crawling-crow/wiki/User-Interface
- [x] Hovedmenyen
- [x] Spillvindu
- [x] Reboots og Damage tokens
- [x] Power down
- [x] Ferdig-knapp
- [x] Kort, hva de ulike fargene betyr
- [x] Ulike korttypene
- [x] Leaderboard

**Comment by adipid** [comment]
![backup](https://user-images.githubusercontent.com/5453010/81084917-c9fb2580-8ef6-11ea-8ef1-b462d123bc2f.png)

![card_back](https://user-images.githubusercontent.com/5453010/81084923-ca93bc00-8ef6-11ea-9a7b-8b32e360eafc.png)

![cardsinhand](https://user-images.githubusercontent.com/5453010/81084926-cb2c5280-8ef6-11ea-9e1d-bfd62e8eeb02.png)

![cardsinregister](https://user-images.githubusercontent.com/5453010/81084929-cbc4e900-8ef6-11ea-8465-33e46ca594ad.png)

![gamewindow](https://user-images.githubusercontent.com/5453010/81084930-cc5d7f80-8ef6-11ea-988c-fa6de53ff91c.png)

![leaderboard](https://user-images.githubusercontent.com/5453010/81084941-cf587000-8ef6-11ea-947b-96dc9345a69a.png)

![leaderboard2](https://user-images.githubusercontent.com/5453010/81084942-cff10680-8ef6-11ea-9f9b-2a6d56b49b4c.png)

![move_1](https://user-images.githubusercontent.com/5453010/81084944-d0899d00-8ef6-11ea-9312-58a95f100b75.png)

![move_2](https://user-images.githubusercontent.com/5453010/81084947-d0899d00-8ef6-11ea-8d8e-08a76bfcccce.png)

![move_3](https://user-images.githubusercontent.com/5453010/81084951-d1223380-8ef6-11ea-8764-34df3d523825.png)

![rotate_left](https://user-images.githubusercontent.com/5453010/81084954-d1baca00-8ef6-11ea-9a6b-1bdbda3863c3.png)

![rotate_right](https://user-images.githubusercontent.com/5453010/81084956-d1baca00-8ef6-11ea-8bae-5e3e22b5ed02.png)

![u_turn](https://user-images.githubusercontent.com/5453010/81084957-d2536080-8ef6-11ea-942a-b26b690b65b3.png)

**Comment by adipid** [comment]
@puj009 Du kan fullføre denne, hvis du får tid :)

**Comment by adipid** [comment]
Veldig likt det som blir gjort i #208 nå

**Comment by thomashusebo** [comment]
Noe er likt, men det fortsatt ulikt nok til at jeg tenker det er verdt å ha begge. 
ui-elements fokuserer på å forklare elementene man ser i spillet
hvordan spille, fokuserer på hvordan man interagerer med spillet
