### ISSUE TITLE
Debug controls, manual tests, and "how to play"

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#208]
Denne issuen inneholder flere momenter, men de henger veldig sammen og må gjøres i rekkefølge, så holder dette samlet.

**1. Debug controls**
- [x] Oppdatér hvilke hvilke input som skal være mulig å bruke i "Debug Mode"

**2. Manuel tests**
- [x] Flytte manuelle tester fra readme til wiki (bruk link i stedet)
- [x] Oppdater/legge til manuelle tester

**3. How to play (and debug)**
- [x] Flytt spill instrukser fra readme til wiki (bruk link i stedet)
- [x] Oppdater spillinstruks
- <s>Legg til spillinstruksvideo</s> Nedprioritert
- [x] Legg til demovideo av spillet

**Comment by adipid** [comment]
Lagde små knapper for å ha litt visuelle endringer:
![restart-button-small](https://user-images.githubusercontent.com/5453010/81398170-fdbd9180-9128-11ea-8f23-85b875a0d0cb.png)

![exit-button-small](https://user-images.githubusercontent.com/5453010/81398172-fe562800-9128-11ea-9d59-be372a0d8b05.png)
