### ISSUE TITLE
Refactor Game Logic from UI

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#21]
- [x] Split `IRobot` into `IRobot` and `IUIRobot`
- [x] Split `GameBoard` into `IGameBoard` and `IUIGameBoard`

**Comment by adipid** [comment]
![seperate-game-ui](https://user-images.githubusercontent.com/5453010/74315475-cd5b9680-4d77-11ea-99d0-248b69e093cb.png)
