### ISSUE TITLE
[BUG] Cannot open menu when programming cards

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#216]
Tittel sier alt. Input fra tastatur fungerer ikke når man programmerer kort, men man burde vel ha tilgang på menyen hele tiden?

**Comment by buzzdead** [comment]
Burde timeren stoppe da?

**Comment by adipid** [comment]
> Burde timeren stoppe da?

Tja, har vel ikke så mye å si. Det kan vel egentlig bare gjøre det synes nå jeg.

**Comment by thomashusebo** [comment]
> Burde timeren stoppe da?

Godt spørsmål. Jeg ser to alternativ:
- Enten så stopper timer
- Eller så fortsetter timer, men da må timer være synlig i menyen

Er forsåvidt samme for meg

**Comment by buzzdead** [comment]
Altså, hvis man skal gå til menyen bare for å skifte på volume eller game speed så er det utrolig teit om  spillet fortsetter å går, period.

**Comment by thomashusebo** [comment]
Hehe. Hvis det ikke er et spørsmål, så er det ikke nødvendig å stille det heller. Hehe

**Comment by buzzdead** [comment]
Kan egentlig være en user story til forrige issuet og menyen det her..
