### ISSUE TITLE
[BUG] When selecting a map, large map is visible in background

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#217]
Tittel sier det meste, se bildet.

![image](https://user-images.githubusercontent.com/45336748/81196577-85878c80-8fbf-11ea-8339-094cdc6283a4.png)

**Comment by buzzdead** [comment]
Kommer nok av noen endringer jeg gjorde, tror det er relativt lett å ordne dette. 
Tenkte jeg skulle ta en økt etter dere.
