### ISSUE TITLE
[BUG] Leaderboard-name continues to update if you stand still on flag

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#222]
Posisjonen på leaderboard-navnet oppdaterer seg hvis man blir stående på flagget.

![Skjermopptak 2020-05-06 kl  20 38 04](https://user-images.githubusercontent.com/5453010/81215535-cb514e80-8fd9-11ea-9a5a-735548b8cad0.gif)

**Comment by buzzdead** [comment]
hehe...
