### ISSUE TITLE
Slower game speed

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#224]
Etter å ha sett på noen av de presentasjonene i går burde vi kanskje revurdere hastighetene vi har på spillet. Sånn som det er nå så er det knapt mulig å få med seg hva som skjer på den treigeste hastigheten. Hvis det går litt treigere så gir det kanskje mening å se hva slags kort de andre robotene spiller også.

**Comment by adipid** [comment]
Dette er ingen dum ide, men vi bør prioritere å få på plass andre ting og fikse bugs nå 😅

**Comment by buzzdead** [comment]
Hehe, er bare å skifte på noen tall da i Events :) Men burde ta det i lag slik at vi blir enige.

**Comment by buzzdead** [comment]
Fant ut at det var greit slik som det var, bare snakk om å kjøre spillet i normal hastighet om man vil ha en virkelighets opplevelse.
