### ISSUE TITLE
Refactor menu

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#227]
Såpass omfattende sak at jeg legger opp issue med kriterier, foregår i refactor/menu branchen.

- [x] Labels til egen klasse

- [x] Refaktorere det i drawMenu til to metoder, drawMainMenu() og drawMapChangeMenu()

**Comment by adipid** [comment]
Kanskje kalle den `drawChangeMapMenu()` i stedenfor `drawMapChangeMenu()`? Ikke så nøye, bare min mening hehe

**Comment by adipid** [comment]
Fikser vi mer på denne?

**Comment by buzzdead** [comment]
Nei, får ikke tid til å begynne med dette nå.
