### ISSUE TITLE
[BUG] Play a song not working

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#237]
Knappen sluttet å fungere i eller etter denne commit'en ser jeg i loggen; fc7568bd

Se også #249

**Comment by buzzdead** [comment]
Tar dette i morgen! Er mulig vi må vurdere om det er royalty fee på den sangen jeg har lagt til, bare legge til en random free sang av noe slag kanskje... kan være en morsom sak å legge til før innlevering i morgen!
