### ISSUE TITLE
[BUG] Nothing happen when loose the game when destroying your robot, by using all reboots

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#240]
Hvis man taper spillet så skjer det ingenting. 
Dette er kanskje mer manglende funksjonalitet enn en bug.
Hvordan reprodusere dette: Bruk opp alle reboots, og så ødelegg roboten igjen.

**Comment by adipid** [comment]
Burde vel bare ende spille på samme måte som når man taper mot en robot.

**Comment by buzzdead** [comment]
Om vi ikke får tid til å fikse dette så er det ikke verdens undergang da man har muligheten til å bare gå tilbake til menyen og avslutte spillet og starte på nytt eventuelt... kanskje man bare kunne fått opp en beskjed fra messageLabel?
