### ISSUE TITLE
[Code] Rearrange Code

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#242]
#162
For at kode skal være enkelt å lese så er det noen prinsipper å følge:
I utgangspunktet ønsker man strukturen slik: fra public til private, og alt i mellom følger den samm retningen.. f.eks public metoder, så protected metoder, så private metoder helt nederst i klassen.

En annen regel er at metoder som kaller på andre metoder skal alltid stå over den metoden den kaller på.

En tredje ting vi kanskje burde tenke på er å kikke litt igjennom koden vår, jeg er sikker på at det er endel kode som blir kalt på flere steder i en klasse, hvor det er mulig å opprette en metode som innebærer forskjellige ting som blir kalt på flere steder.

Jeg foreslår at vi setter av en time til det her i morra, hvor vi alle sammen går igjennom kode og rearranger det slik at det er ordentlig i forhold til punkt 1 og 2. Det finnes plugins til å gjøre dette, men det er nesten like greit om vi bare deler oss opp og tar litt hver, da får vi samtidig luket ut ting som dette med metode som kaller på metode innenfor en klasse, samtidig dette med kode som blir kjørt flere ganger.

**Comment by adipid** [comment]
Linker til denne, hvis noen lurer;
https://www.oracle.com/java/technologies/javase/codeconventions-fileorganization.html

**Comment by adipid** [comment]
Dette burde forresten bare 1 person gjøre, slik at det blir mest mulig likt overalt, sånn at det ikke blir masse rare konflikter.

**Comment by buzzdead** [comment]
Mange klasser er egentlig ganske greie, men "hotspot" klasser slik som animateevent, gameview, menu osv er det nok behov for en liten overhaling i forhold til dette.

**Comment by buzzdead** [comment]
Dette ble gjort i felles i  78b94f7bc235ee4cabd8d931808da1ddb7a42cd0
