### ISSUE TITLE
 [Code] Unified Modeling Language Diagram

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#243]
Prøve å få lagt med en skikkelig UML som gir en god beskrivelse av prosjektet uten å være for omfattende eller for lite inkluderende. Beste er nok sikkert nesten å tegne det for hånd.

Hvis det er mange klasser, så tar man med de viktigste:
GameView, AnimateEvent, Register, Robot (også RobotLogic) som operasjonelle klasser.

Ting som layers, phase, round, game, cards osv er mer passive klasser.

Ting som AssetManager, meny, controls, grid, gameboard har mer en spesifikk plass i programmet.

**Comment by ljo071** [comment]
![klassediagram-oblig4](https://user-images.githubusercontent.com/59846048/81407446-b391db80-913b-11ea-8244-0b5d6b1d3707.png)
