### ISSUE TITLE
[BUG] Gamespeed - not starting as normal

### ISSUE THREAD

**Issue by ljo071** [inf112-v20/crawling-crow#250]
Når du åpner spillet står spillhastigheten på normal men den starter egentlig på fast.
Når du går fra fast/fastest tilbake til normal så får du den egentlig normal hastigheten.

**Comment by thomashusebo** [comment]
Manuell test: [6.1](https://github.com/inf112-v20/crawling-crow/wiki/Tester#6-spillhastighet)
