### ISSUE TITLE
Win a game

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#27]
Implementere en vinnende tilstand, som sier: "You won the game!" elns.

- [x] Trenger at informasjon om hvilke flagg en robot har besøkt ligger lagret og tilgjengelig
- [x] Trenger å sjekke om noen har funnet i rett steg i spillet

**Comment by thomashusebo** [comment]
Fra manualen: 
"The winner is the first player to touch all the flags in order. The game can end as soon as the
winner touches the last flag, or play can continue to determine runners-up"

Trenger:
- [ ] Trenger at informasjon om hvilke flagg en robot har besøkt ligger lagret og tilgjengelig
- [ ] Trenger å sjekke om noen har funnet i rett steg i spillet

**Comment by thomashusebo** [comment]
Har desverre glemt å tagge commit hvor dette ble implementert. Men er er commit med siste hovedendring. En spiller som har besøkt alle flag vinner spillet

57dc4919f7f38b92f82b6a5bb7f314e111904af1

**Comment by adipid** [comment]
Sjekker om vinner eksiterer ved å trykke <kbd>W</kbd>
