### ISSUE TITLE
Implement simple AI

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#31]
Simple AI to move after game objectives and avoid danger.

Reopened for refactoring and further implementation of the advanced version.

Def done: #142

**Comment by adipid** [comment]
@buzzdead implementerte dette i c064641

**Comment by adipid** [comment]
Kan vi anse denne som fullført nå? :)

**Comment by buzzdead** [comment]
Er noen småting jeg har tenkt å gjøre før jeg er ferdig med den, og er jo fortsatt også flere vanskelighetsgrader som nice to have. Skal håndtere den når jeg får tid.

**Comment by adipid** [comment]
Hvordan ligger vi an her? Denne burde vel være ferdig til vi skal ha presentasjonen på tirsdag.

**Comment by buzzdead** [comment]
Er nok ferdig til tirsdag.

**Comment by adipid** [comment]
Skal vi anse denne som ferdig, da det er litt sent å fortsette med det nå mtp alt annet vi har å gjøre?

**Comment by buzzdead** [comment]
se hva vi får gjort til i morra.

**Comment by adipid** [comment]
Burde nok prioritere bugfixes osv først
