### ISSUE TITLE
Program Cards

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#33]
Enkel implemtentasjon av programkort.

- [x] Generere kort
- [x] Hente kort
- [x] Tilfeldig prioritet på kortene mellom 1 til 500

**Comment by adipid** [comment]
Se side 4 i rulebook.
<img width="238" alt="Skjermbilde 2020-02-19 kl  09 26 54" src="https://user-images.githubusercontent.com/5453010/74815681-f9d45d00-52f9-11ea-9c26-a074dbe4f653.png">

**Comment by adipid** [comment]
Klassen er nå implementert i `ProgramCards` og bruker _enum_ for `CardTypes`.

`CardTypes` inneholder alle de ulike korttypene vi MÅ ha til MVP versjonen av spillet.

`ProgramCards` inneholder også klassen `Card` som blir brukt når de ulike programkortene blir generert av `ProgramCards()`.

Kortene blir lagret i en `ArrayList()` som heter `deckOfCards`
