### ISSUE TITLE
Documentation in README

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#35]
Forklare hvordan man kjører programmet og kjører tester osv.

- [x] Instruksjoner
- [x] Testinstruksjoner
- [x] Manuelle testinstruksjoner
- [x] Kjørbart på Linux, Windows og macOS
- [x] Klassediagram

**Comment by thomashusebo** [comment]
![Oblig2UML](https://user-images.githubusercontent.com/45336748/75541155-b1b1ea80-5a1d-11ea-8a34-e57d7586e76a.png)

**Comment by thomashusebo** [comment]
[Oblig2UML.pdf](https://github.com/inf112-v20/crawling-crow/files/4266569/Oblig2UML.pdf)
