### ISSUE TITLE
Create a simple Game class

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#36]
Game klassen er ment å håndtere når ting skjer i spillet. Foreløpig innebærer dette:

- [x] Skal sette opp nytt brett
- [x] Skal håndtere hvordan runder gjennomføres
- [x] Skal håndtere hvordan faser gjennomføres
- [x] Skal håndtere hvordan steg gjennomføres

**Comment by adipid** [comment]
@thomashusebo Som "object" mener du en klasse? Et game object høres ut som noe som er et objekt i selve spillet.

**Comment by thomashusebo** [comment]
> @thomashusebo Som "object" mener du en klasse? Et game object høres ut som noe som er et objekt i selve spillet.

Ja, mener klasse

**Comment by thomashusebo** [comment]
har laget gameobject, or merget inn i obligatorisk2.
Ønsker å flytte movement.
```
IGame game = new Game();
game.startGame() 
```
Resulterer til slutt i steget--------->
`moveRobots()`
Ønsker at det skal lyttes til tastetrykk for robotbevegelse inn hit. Noen som har en ide om hvordan dette kan gå seg til. Eller om hva som er en bedre på lytte til tastetrykk i en spesifikk del av programmet

**Comment by adipid** [comment]
@thomashusebo Hvis du er helt ferdig med denne så burde du lukke **Issue*'en.

**Comment by thomashusebo** [comment]
Foreløpig er dette bare et skall, men som kan fylles inn etterhvert.

Spillet har tre states foreløpig.

- Om spillet kjører (boolean)
- I hvilket steg av runden spillet er (enum, RoundStep)
- I hvilket steg av fasen spillet er (enum, PhaseStep)
