### ISSUE TITLE
AssetsManager needs to have specific call order on getLoadedMap() and getMap()

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#37]
For å bruke funksjonen `getLoadedMap()`, er det nødvendig at funksjonen `getMap()` er blitt kalt før. Dette var ikke lett å se. Fikk feilmeldinger for dette. 
- [x] Fix 1: `getMap()` er funksjonen som setter layers, men dette er ikke intuitivt. Endre navn eller noe
- [x] Fix 2: Det er ingen sjekk/garanti for `getLoadedMap()`. Den returnerer `null` hvis det ikke er noe map som er `loaded`. Endre navn, sett inn precondition, eller sørg for å sette Map hvis den ikke enda er satt

**Comment by adipid** [comment]
Trenger en bedre tittel på Issue, AssetManager er for generelt.

**Comment by buzzdead** [comment]
Altså: getMap() er metoden som returnerer mappet man ønsker å spille. Ved å opprette et map så oppretter man alle lagene som finnes for dette mappet. Disse lagene finner man igjen ved å ha tilgang til kartet i minnet, lagrer derfor denne posisjonen i minnet til en variabel kalt loadedMap som videre brukes til å lage nye Layers instanser rundt omkring i systemet uten å lage noe nytt i det hele tatt.
