### ISSUE TITLE
Use Lambda Expressions

### ISSUE THREAD

**Issue by thomashusebo** [inf112-v20/crawling-crow#39]
Får feilmelding "Lambda expressions are not supported at language level '7'". Hvis dette kan endres er det ønskelig.

**Comment by adipid** [comment]
@thomashusebo 
Denne er vel løst nå, med hva jeg påpekte via Slack?
<img width="900" alt="Skjermbilde 2020-02-20 kl  17 11 18" src="https://user-images.githubusercontent.com/5453010/74963412-f7fdbd00-5411-11ea-8728-6078cb8c66ce.png">

**Comment by thomashusebo** [comment]
> @thomashusebo
> Denne er vel løst nå, med hva jeg påpekte via Slack?
> <img alt="Skjermbilde 2020-02-20 kl 17 11 18" width="900" src="https://user-images.githubusercontent.com/5453010/74963412-f7fdbd00-5411-11ea-8728-6078cb8c66ce.png">

Det er helt korrekt. Løse seg når jeg endret til language level 11
