### ISSUE TITLE
Enhanced Layers

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#40]
For å gjøre metodekall inne i **Layers** klassen så er det mulig å oppdatere litt. Foreløpig kaller man opp et layer, også sjekker man en celle inne i dette layeret. Dette er for tiden det samme for alle layers utenrom robot layeret, hvor man ønsker både å finne ut om det er noe i en gitt celle i layeret, eller om man ønsker å bruke setCell for å plassere noe i layeret. Derfor planlegger jeg å implementere en optimalisert versjon slik som behovet er nå, hvor f.eks if ( layers.getWall().getCell(2,3)!=null ) blir forkortet til if (layers.getWall(2,3)). Dette ved at man inkluderer floats x og y i layers.getWall(2.0, 3.0), og sjekker en celle i wall-layeret med disse tallene for null value. For robot layeret lager man da en set metode for å utføre plasserings operasjoner. 

- [x] Make layers check the specific layer if it exists at all 
- [x] Make get method for ID for a specific Cell in a specific Layer
- [x] Make a complementary set method to update a cells value for the robots layer. 

Lukkes for nå, blir helt sikkert praktisk å legge til setCell, getCell og getID for flere layers etterhvert som vi utvikler spillet.

**Comment by buzzdead** [comment]
Satt denne til "question" da jeg er usikker på behovet, men kanskje man kan komme tilbake til dette issuet om en liten stund. Hvis man ser bl.a på metoder som isBlocked, isOnFlag og isOnHole i BooleanCalcuator så ser man at det kanskje ikke er nødvendig.

**Comment by thomashusebo** [comment]
Ved første øyekast ser det ut som GridPoint2 er mer nyttig enn Vector2 for oss ja, da vi bare bruker int uansett. 👍
