### ISSUE TITLE
Create new visual representation of Robot

### ISSUE THREAD

**Issue by puj009** [inf112-v20/crawling-crow#41]

**Comment by adipid** [comment]
Skal lage flere states på disse og lage det i PNG med gjennomsiktig bakgrunn.

**Comment by puj009** [comment]
![image](https://user-images.githubusercontent.com/59871266/75254999-8ba00680-57e1-11ea-9f71-ada648828bd8.png)

**Comment by adipid** [comment]
Har nå vektorisert de @puj009 har laget, og kan enkelt endre på dem dersom det skulle trengs. Så lukker saken, trenger vi å oppdatere robot designene, så lager vi enten ny issue eller så fikser vi det bare!
