### ISSUE TITLE
Walls

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#42]
- [x] Veggene skal være slik at om roboten beveger seg i en celle i retning mot en vegg, eller til en celle i retning mot en vegg så skal den stoppes.

- [x] Veggene skal være slik at om en robot står mellom en vegg og en annen robot, så vil roboten telles som blokkerende for den andre roboten

- [x] Punkt to skal følge rekursivt.

La til dette som en del-metode for rutinesjekk ved håndtering av mulige tilfeller som oppstår når roboten beveger seg, om den blir blokkert eller om den havner i tumulter med andre roboter. Ved hjelp av ID (fra tiles settet) til de forskjellige veggene relativt til hvordan man beveger seg.

**Comment by buzzdead** [comment]
[SimiliarUserStory](https://github.com/inf112-v20/crawling-crow/projects/2#card-33006101)

- [ ] Veggene skal være slik at om roboten beveger seg i en celle i retning mot en vegg, eller til en celle i retning mot en vegg så skal den stoppes.

- [ ] Veggene skal være slik at om en robot står mellom en vegg og en annen robot, så vil roboten telles som blokkerende for den andre roboten

- [ ] Punkt to skal følge rekursivt.

**Comment by adipid** [comment]
@buzzdead Kan du forklare i koden og her hvordan du har gjort dette?
