### ISSUE TITLE
Som <spiller> trenger jeg at <roboter stopper lasere> slik at jeg <kan gjemme meg bak andre roboter>

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#43]
# Akseptansekriterier

- [x] Hvis roboten går steller seg i laseren så skal den delen av laseren på motsatt side av roboten hvor laseren peker forsvinne.

- [x] Hvis roboten går ut av laseren så skal laseren komme tilbake.

- [x] Hvis roboten beveger seg -langs- laseren så skal enten en større del av laseren forsvinne eller så skal avstanden roboten beveger seg i retning fra laseren gjenopprettes.

# Definisjonen av ferdig
- Å få til at tilogmed når en robot går langt ute i laseren, og en annen robot går langt inne i laseren, så skal ikke den delen førstkommende robot blokkerte gjenopprettes når denne roboten går vekk igjen.
- Et oversiktlig system som kan holde på flere instanser av roboter som har bevegd seg i lasere, og som stabilt kan fjerne og gjenopprette lasere i selv den mest hektiske situasjon.

- Laser kannonene skal holde på sine egne posisjoner, ikke robotene som går inn i de.
Laser update (lignende fire laser) i steden for å holde styr på hvert enkelt celle.
- [x] #85

**Comment by buzzdead** [comment]
Done
