### ISSUE TITLE
Som <spiller> trenger jeg at <rekkefølgen på bevegelser i en fase er avgjort av prioritering> for <å følge spillets regler>

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#54]
## Akseptansekriterier
- [x] `Robot` med høyeste priortering på programkortet utfører først, også den med nest høyest osv.
- [x] Programkort må ha en prioritering.

## Definisjonen av ferdig
- [x] #33, mtp. at kortene må ha en prioritering.
- [x] Flere spiller-roboter deler denne oppførselen.

**Comment by thomashusebo** [comment]
Fikset for flerspillere her: 9beb6ad0fba27b958835a0a03fc18ddd70d0fecd
