### ISSUE TITLE
Som <spiller> trenger jeg <å bli tildelt kort på starten av runden min> slik <at jeg kan programmere roboten min>

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#59]
## Akseptansekriterier
- [x] Spiller må se hvilke kort den har
- ~~Se hvilke kort de ulike robot/spillerene har~~, se #106

## Definisjonen av ferdig
- [x] #82

**Comment by buzzdead** [comment]
Bør vel kanskje vurdere hvor mye informasjon som faktisk skal iverksettes i forhold til dette. Det holder vel egentlig at spilleren selv ser kortene sine, spørsmålet er kanskje heller hvordan man håndterer situasjonen etter spilleren har valgt kortene sine. Kanskje kan de forsvinne en etter en ettersom fasene går.

**Comment by adipid** [comment]
> Det holder vel egentlig at spilleren selv ser kortene sine

Det er forsåvidt sant, men man burde kunne håndtere dette på en god måte mtp. når vi skal implementere nettverk. (Når vi ikke skal spille mot AI)

**Comment by adipid** [comment]
Opprettet en ny issue basert på det ene akseptansekriterie, #106.

Anser denne som ferdig imlementert nå.
