### ISSUE TITLE
Som <spiller> trenger jeg <å kunne få et alternativkort> for <å opprettholde reglene i spillet>

### ISSUE THREAD

**Issue by timharek** [inf112-v20/crawling-crow#69]
## Akseptansekriterier
- 
- 

## Definisjonen av ferdig
- 
-

**Comment by buzzdead** [comment]
Er det noen som har noe formening om dette? Ser det ikke er lagt til noen kriterier.. Det finnes idéer der ute for hva vi kan legge til.

**Comment by adipid** [comment]
Trenger ikke å lukke den, er jo ikke noe som er implementert og det er jo bare Nice to have.
