### ISSUE TITLE
Robots and Lasers

### ISSUE THREAD

**Issue by buzzdead** [inf112-v20/crawling-crow#85]
Dette er implementasjon av userstory: #43 og #44 
Detaljert forklaring av kriterier og hva som midlertidig er oppnådd finnes der.

**Comment by buzzdead** [comment]
Hovedarbeidet er gjort, mangler implementasjon for laser som går oppover, og laser som går motsatt retning av den jeg allerede har lagt til, men det er stort sett mer av det samme og det er bare snakk om å refaktorere litte granne og gjøre det på best mulig måte.

**Comment by adipid** [comment]
Anser denne som ferdig da lasere gjør alt som er nødvendig for øyeblikket, lag ny Issue dersom det er noen utbedringer som skal på plass.
