### ISSUE TITLE
[UI] Main menu 

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#92]
En fin hovedmeny hvor man kan starte spill, avslutte spill og er skalerbart med flere funskjoner som flerspiller.

- [x] Starte spill
- [x] Avslutte spill
- [x] Rom for flere alternativer.

Definisjon av ferdig:
Refaktorert både strukturen og koden.

**Comment by adipid** [comment]
Ut i fra de tutorialene jeg fant på dette, så må vi refaktorere en del for å få det til å fungere:
https://www.youtube.com/watch?v=67ZCQt8QpNA&t=228s

**Comment by buzzdead** [comment]
En konkret måte å gjøre det på må vel å være at man har en grafisk metode som kjøres ved oppstart, altså en meny. Ut ifra denne menyen kan man ha en klasse som setter om alle valgmulighetene ifra menyen til variabler, og som kjøres sammen med UI når spillet startes.

**Comment by buzzdead** [comment]
Her er oppskrift på hvordan man lett kan lage "buttons" ut av tekstur og legge til eventlisteners, for å lage funksjonelle "click events" på det man måtte ønske inne i menyen.
https://gamedev.stackexchange.com/questions/121115/libgdx-simple-button-with-image

**Comment by adipid** [comment]
Basis-elementene for hovedmenyen er nå implementert og trenger ikke å ha denne Issue'en liggende lenger.

**Comment by adipid** [comment]
Man kan alltids forbedre menyen, men det er på plass.

**Comment by adipid** [comment]
Har faktisk også implementert #19

**Comment by buzzdead** [comment]
Er implementert for å fungere men ikke for å være fungerbar som en klasse kan man si. En heftig refaktorering skal til!

**Comment by adipid** [comment]
> Er implementert for å fungere men ikke for å være fungerbar som en klasse kan man si. En heftig refaktorering skal til!

Ta ev. å lag en ny issue på det, og beskriv hva du tenker å gjøre :)
