### ISSUE TITLE
[BUG] Laser-image should be from the tiles.png

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#93]
Laser image should be from the tiles.png and not seperate files.

**Comment by buzzdead** [comment]
Ja. Har ikke funnet ut hvordan man henter de ut direkte fra tiles uten å ha de implementert på mappet enda..

**Comment by buzzdead** [comment]
Fixed this with a get Tiled Sets method in AssetsManagerUtil.
