### ISSUE TITLE
Optimize AssetManager

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#94]
Det er for mange deklareringer, og krever at vi hardkoder hver nye robot, map osv...

Burde ha løkker for å hente ut hva som ligger i de ulike mappene og slikt.

**Comment by buzzdead** [comment]
Det som var tenkt når jeg begynte på den her, bare gjør ting enkelt til å begynne med så faller det naturlig hvordan man setter det opp når det blir klart hvor ting skal være. Egentlig bør vel kun ting som har med tekstur å gjøre ligge der.

**Comment by buzzdead** [comment]
Skal vi bare la assetmanager være slik som den er ? Den inneholder fortsatt liste med roboter, robotnavn etc.. Vi kunne kanskje vurdert å hvertfall lagd en egen klasse for dette hvis vi ikke tar oss tid til å gjøre det enda bedre..

**Comment by adipid** [comment]
Er enig, den fungerer fint, så vi kan egentlig bare lukke denne.

**Comment by adipid** [comment]
Nå vil jeg si at alt ser veldig ryddig og oversiktlig ut, så lukker denne mtp #181!
