### ISSUE TITLE
Tiled Translator

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#95]
Oversetter logikken fra tiled til vår egen kode.

**Comment by buzzdead** [comment]
Kan være fornuftig å gjøre klassen tilgjengelig uten å måtte initialisere den. Den endrer ikke form eller innhold.

**Comment by thomashusebo** [comment]
@adipid  Er denne egentlig ferdig eller manger vi noe her?

**Comment by adipid** [comment]
Den er jo implementert nå, mangler vi noe lager vi bare ny issue på den :)
