### ISSUE TITLE
Cleanup after 2nd assignment

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#96]
Det er mye unødvendig kode etter oblig2, så kan optimaliseres.

EDIT (@thomashusebo  ):
Har flyttet (nesten) alle metoder fra booleanCalc til layers, ettersom alle disse metodene i utgangspunktet bare manipulerte eller sjekket layers objektet. 

Alle de flyttede metodene ligger foreløpig som default metoder i interfacen (fordi det var dette Intellij sin refactor-hjelp kunne gjøre).

- [x] Flytte metodekropp fra ILayers til Layers
- [x] Videre refaktorere ansvar i layers. (eventuelt opp til gameboard e.l.)

Ellers: Det er noe kode igjen i BooleanCalc, men jeg tror alt dette er utdatert, men rakk ikke å trygt gå gjennom dette. 

- [x] Gå igjennom restererende BooleanCalc og vurderer om dette kan slettes, eventuelt flyttes.

**Comment by buzzdead** [comment]
Jepp, gir det kanskje mening at man har en klasse som extender layers heller enn å presse alle metodene inn i layers? En movement klasse som extender layers, med alle sjekkene osv.

**Comment by thomashusebo** [comment]
> Jepp, gir det kanskje mening at man har en klasse som extender layers heller enn å presse alle metodene inn i layers? En movement klasse som extender layers, med alle sjekkene osv.

Ja, noe i den dur😊 kan være lurt om vi parprogrammerer dette, siden det er mest for forståelsen til alle sin del 😊

**Comment by buzzdead** [comment]
Ja enig, roboten kan jo for eksempel videre extende movement. Slik blir det veldig ryddig i Robot klassen. Kanskje man til og med få til å gjøre metodene private i de klassene som extender layers.

**Comment by thomashusebo** [comment]
Mye har skjedd uten kommentarer i denne saken. Oppsummerer raskt: 

Ansvar som ble flyttet ILayers er nå flyttet til Listener klasser av Sigmund
Ansvar fra boolean calculator er refacoterert ut til passende klasser.
