### ISSUE TITLE
RobotState and Robot have to many similiarities

### ISSUE THREAD

**Issue by adipid** [inf112-v20/crawling-crow#97]
De har begge mange like metoder, og testene til `RobotState`-klassen bruker bare av metodene `Robot`-klassen. Dette må vi få gjort noe med, enten ved å extende el.

**Comment by buzzdead** [comment]
Ser det er mange funksjoner i robot som hører hjemme i robotstate, slik som noe av dette med direksjon, alle flagg metodene. Må selvfølgelig fortsatt ha et par metoder i Robot til å sende informasjonen videre til view (RobotUI).

**Comment by adipid** [comment]
Denne er ikke relevant lenger, da vi har skilt ut enda mer og gitt en bedre definisjon på hva de ulike klassene gjør.
